# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nanogen.ui'
#
# Created: Thu Mar 13 14:20:52 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NanoGen(object):
    def setupUi(self, NanoGen):
        NanoGen.setObjectName(_fromUtf8("NanoGen"))
        NanoGen.resize(520, 641)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans Unicode"))
        font.setPointSize(14)
        NanoGen.setFont(font)
        self.centralwidget = QtGui.QWidget(NanoGen)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.nanotube_generators = QtGui.QWidget()
        self.nanotube_generators.setObjectName(_fromUtf8("nanotube_generators"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.nanotube_generators)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.nanotube_generator_radioButton = QtGui.QRadioButton(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nanotube_generator_radioButton.setFont(font)
        self.nanotube_generator_radioButton.setChecked(True)
        self.nanotube_generator_radioButton.setObjectName(_fromUtf8("nanotube_generator_radioButton"))
        self.nanotube_generator_buttonGroup = QtGui.QButtonGroup(NanoGen)
        self.nanotube_generator_buttonGroup.setObjectName(_fromUtf8("nanotube_generator_buttonGroup"))
        self.nanotube_generator_buttonGroup.addButton(self.nanotube_generator_radioButton)
        self.verticalLayout_2.addWidget(self.nanotube_generator_radioButton)
        self.mwnt_generator_radioButton = QtGui.QRadioButton(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mwnt_generator_radioButton.setFont(font)
        self.mwnt_generator_radioButton.setObjectName(_fromUtf8("mwnt_generator_radioButton"))
        self.nanotube_generator_buttonGroup.addButton(self.mwnt_generator_radioButton)
        self.verticalLayout_2.addWidget(self.mwnt_generator_radioButton)
        self.unrolled_nanotube_generator_radioButton = QtGui.QRadioButton(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.unrolled_nanotube_generator_radioButton.setFont(font)
        self.unrolled_nanotube_generator_radioButton.setObjectName(_fromUtf8("unrolled_nanotube_generator_radioButton"))
        self.nanotube_generator_buttonGroup.addButton(self.unrolled_nanotube_generator_radioButton)
        self.verticalLayout_2.addWidget(self.unrolled_nanotube_generator_radioButton)
        self.bundle_generator_checkBox = QtGui.QCheckBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bundle_generator_checkBox.setFont(font)
        self.bundle_generator_checkBox.setCheckable(True)
        self.bundle_generator_checkBox.setObjectName(_fromUtf8("bundle_generator_checkBox"))
        self.verticalLayout_2.addWidget(self.bundle_generator_checkBox)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.nanotube_generators)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.n_spinBox = QtGui.QSpinBox(self.nanotube_generators)
        self.n_spinBox.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.n_spinBox.setFont(font)
        self.n_spinBox.setMaximum(100)
        self.n_spinBox.setProperty("value", 10)
        self.n_spinBox.setObjectName(_fromUtf8("n_spinBox"))
        self.horizontalLayout_2.addWidget(self.n_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.m_spinBox = QtGui.QSpinBox(self.nanotube_generators)
        self.m_spinBox.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        self.m_spinBox.setFont(font)
        self.m_spinBox.setMaximum(100)
        self.m_spinBox.setProperty("value", 10)
        self.m_spinBox.setObjectName(_fromUtf8("m_spinBox"))
        self.horizontalLayout.addWidget(self.m_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.line_2 = QtGui.QFrame(self.nanotube_generators)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.nx_spinBox = QtGui.QSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nx_spinBox.setFont(font)
        self.nx_spinBox.setMinimum(1)
        self.nx_spinBox.setObjectName(_fromUtf8("nx_spinBox"))
        self.horizontalLayout_4.addWidget(self.nx_spinBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.Lx_doubleSpinBox = QtGui.QDoubleSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Lx_doubleSpinBox.setFont(font)
        self.Lx_doubleSpinBox.setReadOnly(True)
        self.Lx_doubleSpinBox.setDecimals(4)
        self.Lx_doubleSpinBox.setObjectName(_fromUtf8("Lx_doubleSpinBox"))
        self.horizontalLayout_7.addWidget(self.Lx_doubleSpinBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.ny_spinBox = QtGui.QSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ny_spinBox.setFont(font)
        self.ny_spinBox.setMinimum(1)
        self.ny_spinBox.setObjectName(_fromUtf8("ny_spinBox"))
        self.horizontalLayout_5.addWidget(self.ny_spinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.Ly_doubleSpinBox = QtGui.QDoubleSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Ly_doubleSpinBox.setFont(font)
        self.Ly_doubleSpinBox.setReadOnly(True)
        self.Ly_doubleSpinBox.setDecimals(4)
        self.Ly_doubleSpinBox.setObjectName(_fromUtf8("Ly_doubleSpinBox"))
        self.horizontalLayout_8.addWidget(self.Ly_doubleSpinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.nz_spinBox = QtGui.QSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nz_spinBox.setFont(font)
        self.nz_spinBox.setMinimum(1)
        self.nz_spinBox.setObjectName(_fromUtf8("nz_spinBox"))
        self.horizontalLayout_6.addWidget(self.nz_spinBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.Lz_doubleSpinBox = QtGui.QDoubleSpinBox(self.nanotube_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Lz_doubleSpinBox.setFont(font)
        self.Lz_doubleSpinBox.setDecimals(4)
        self.Lz_doubleSpinBox.setObjectName(_fromUtf8("Lz_doubleSpinBox"))
        self.horizontalLayout_9.addWidget(self.Lz_doubleSpinBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.nanotube_generators)
        self.graphene_generators = QtGui.QWidget()
        self.graphene_generators.setObjectName(_fromUtf8("graphene_generators"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.graphene_generators)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_9 = QtGui.QLabel(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        self.width_doubleSpinBox = QtGui.QDoubleSpinBox(self.graphene_generators)
        self.width_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.width_doubleSpinBox.setFont(font)
        self.width_doubleSpinBox.setDecimals(4)
        self.width_doubleSpinBox.setProperty("value", 1.0)
        self.width_doubleSpinBox.setObjectName(_fromUtf8("width_doubleSpinBox"))
        self.horizontalLayout_16.addWidget(self.width_doubleSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_10 = QtGui.QLabel(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_17.addWidget(self.label_10)
        self.length_doubleSpinBox = QtGui.QDoubleSpinBox(self.graphene_generators)
        self.length_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.length_doubleSpinBox.setFont(font)
        self.length_doubleSpinBox.setDecimals(4)
        self.length_doubleSpinBox.setProperty("value", 10.0)
        self.length_doubleSpinBox.setObjectName(_fromUtf8("length_doubleSpinBox"))
        self.horizontalLayout_17.addWidget(self.length_doubleSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addLayout(self.verticalLayout_9)
        self.line_5 = QtGui.QFrame(self.graphene_generators)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_19.addWidget(self.line_5)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.graphene_generators)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.AC_edge_radioButton = QtGui.QRadioButton(self.graphene_generators)
        self.AC_edge_radioButton.setChecked(True)
        self.AC_edge_radioButton.setObjectName(_fromUtf8("AC_edge_radioButton"))
        self.Ly_edge_buttonGroup = QtGui.QButtonGroup(NanoGen)
        self.Ly_edge_buttonGroup.setObjectName(_fromUtf8("Ly_edge_buttonGroup"))
        self.Ly_edge_buttonGroup.addButton(self.AC_edge_radioButton)
        self.verticalLayout_3.addWidget(self.AC_edge_radioButton)
        self.ZZ_edge_radioButton = QtGui.QRadioButton(self.graphene_generators)
        self.ZZ_edge_radioButton.setObjectName(_fromUtf8("ZZ_edge_radioButton"))
        self.Ly_edge_buttonGroup.addButton(self.ZZ_edge_radioButton)
        self.verticalLayout_3.addWidget(self.ZZ_edge_radioButton)
        self.horizontalLayout_20.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.line_4 = QtGui.QFrame(self.graphene_generators)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_8.addWidget(self.line_4)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_11 = QtGui.QLabel(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.nlayers_spinBox = QtGui.QSpinBox(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nlayers_spinBox.setFont(font)
        self.nlayers_spinBox.setMinimum(1)
        self.nlayers_spinBox.setMaximum(50)
        self.nlayers_spinBox.setObjectName(_fromUtf8("nlayers_spinBox"))
        self.horizontalLayout_18.addWidget(self.nlayers_spinBox)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_18)
        self.line_6 = QtGui.QFrame(self.graphene_generators)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_21.addWidget(self.line_6)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.graphene_generators)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.AA_stacking_radioButton = QtGui.QRadioButton(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AA_stacking_radioButton.setFont(font)
        self.AA_stacking_radioButton.setCheckable(False)
        self.AA_stacking_radioButton.setChecked(False)
        self.AA_stacking_radioButton.setObjectName(_fromUtf8("AA_stacking_radioButton"))
        self.stacking_order_buttonGroup = QtGui.QButtonGroup(NanoGen)
        self.stacking_order_buttonGroup.setObjectName(_fromUtf8("stacking_order_buttonGroup"))
        self.stacking_order_buttonGroup.addButton(self.AA_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AA_stacking_radioButton)
        self.AB_stacking_radioButton = QtGui.QRadioButton(self.graphene_generators)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AB_stacking_radioButton.setFont(font)
        self.AB_stacking_radioButton.setCheckable(False)
        self.AB_stacking_radioButton.setObjectName(_fromUtf8("AB_stacking_radioButton"))
        self.stacking_order_buttonGroup.addButton(self.AB_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AB_stacking_radioButton)
        self.horizontalLayout_22.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_24.addLayout(self.verticalLayout_8)
        spacerItem7 = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.graphene_generators)
        self.verticalLayout_12.addWidget(self.stackedWidget)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_10.addWidget(self.line_3)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cif_radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.cif_radioButton.setFont(font)
        self.cif_radioButton.setCheckable(False)
        self.cif_radioButton.setObjectName(_fromUtf8("cif_radioButton"))
        self.structure_format_buttonGroup = QtGui.QButtonGroup(NanoGen)
        self.structure_format_buttonGroup.setObjectName(_fromUtf8("structure_format_buttonGroup"))
        self.structure_format_buttonGroup.addButton(self.cif_radioButton)
        self.verticalLayout_5.addWidget(self.cif_radioButton)
        self.DATA_radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.DATA_radioButton.setFont(font)
        self.DATA_radioButton.setObjectName(_fromUtf8("DATA_radioButton"))
        self.structure_format_buttonGroup.addButton(self.DATA_radioButton)
        self.verticalLayout_5.addWidget(self.DATA_radioButton)
        self.pdb_radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.pdb_radioButton.setFont(font)
        self.pdb_radioButton.setCheckable(False)
        self.pdb_radioButton.setObjectName(_fromUtf8("pdb_radioButton"))
        self.structure_format_buttonGroup.addButton(self.pdb_radioButton)
        self.verticalLayout_5.addWidget(self.pdb_radioButton)
        self.xyz_radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.xyz_radioButton.setFont(font)
        self.xyz_radioButton.setChecked(True)
        self.xyz_radioButton.setObjectName(_fromUtf8("xyz_radioButton"))
        self.structure_format_buttonGroup.addButton(self.xyz_radioButton)
        self.verticalLayout_5.addWidget(self.xyz_radioButton)
        self.Z_matrix_radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.Z_matrix_radioButton.setFont(font)
        self.Z_matrix_radioButton.setCheckable(False)
        self.Z_matrix_radioButton.setObjectName(_fromUtf8("Z_matrix_radioButton"))
        self.structure_format_buttonGroup.addButton(self.Z_matrix_radioButton)
        self.verticalLayout_5.addWidget(self.Z_matrix_radioButton)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_15.addWidget(self.line_7)
        self.generate_pushButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.generate_pushButton.setFont(font)
        self.generate_pushButton.setObjectName(_fromUtf8("generate_pushButton"))
        self.horizontalLayout_15.addWidget(self.generate_pushButton)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_15)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        NanoGen.setCentralWidget(self.centralwidget)
        self.nanogen_statusBar = QtGui.QStatusBar(NanoGen)
        self.nanogen_statusBar.setObjectName(_fromUtf8("nanogen_statusBar"))
        NanoGen.setStatusBar(self.nanogen_statusBar)

        self.retranslateUi(NanoGen)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NanoGen)

    def retranslateUi(self, NanoGen):
        NanoGen.setWindowTitle(_translate("NanoGen", "NanoGen", None))
        self.nanotube_generator_radioButton.setText(_translate("NanoGen", "Nanotube Generator", None))
        self.mwnt_generator_radioButton.setText(_translate("NanoGen", "Multi-walled Nanotube Generator", None))
        self.unrolled_nanotube_generator_radioButton.setText(_translate("NanoGen", "Unrolled Nanotube Generator", None))
        self.bundle_generator_checkBox.setText(_translate("NanoGen", "Bundle Generator", None))
        self.label_7.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">n = </p></body></html>", None))
        self.label_14.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">m = </p></body></html>", None))
        self.label.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>", None))
        self.label_2.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>", None))
        self.Lx_doubleSpinBox.setSuffix(_translate("NanoGen", " nm", None))
        self.label_3.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>", None))
        self.label_12.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>", None))
        self.Ly_doubleSpinBox.setSuffix(_translate("NanoGen", " nm", None))
        self.label_4.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>", None))
        self.label_13.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>", None))
        self.Lz_doubleSpinBox.setSuffix(_translate("NanoGen", " nm", None))
        self.label_9.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x</span> =</p></body></html>", None))
        self.label_10.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y</span> =</p></body></html>", None))
        self.label_5.setText(_translate("NanoGen", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y</span> edge</p></body></html>", None))
        self.AC_edge_radioButton.setText(_translate("NanoGen", "armchair", None))
        self.ZZ_edge_radioButton.setText(_translate("NanoGen", "zigzag", None))
        self.label_11.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">layers</span> =</p></body></html>", None))
        self.label_6.setText(_translate("NanoGen", "<html><head/><body><p>Stacking Order</p></body></html>", None))
        self.AA_stacking_radioButton.setText(_translate("NanoGen", "AA", None))
        self.AB_stacking_radioButton.setText(_translate("NanoGen", "AB", None))
        self.cif_radioButton.setText(_translate("NanoGen", "cif", None))
        self.DATA_radioButton.setText(_translate("NanoGen", "LAMMPS data", None))
        self.pdb_radioButton.setText(_translate("NanoGen", "pdb", None))
        self.xyz_radioButton.setText(_translate("NanoGen", "xyz", None))
        self.Z_matrix_radioButton.setText(_translate("NanoGen", "Z-matrix", None))
        self.generate_pushButton.setText(_translate("NanoGen", "Generate", None))

