# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swnt_generator.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SWNTGenerator(object):
    def setupUi(self, SWNTGenerator):
        SWNTGenerator.setObjectName("SWNTGenerator")
        SWNTGenerator.resize(427, 436)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SWNTGenerator.sizePolicy().hasHeightForWidth())
        SWNTGenerator.setSizePolicy(sizePolicy)
        SWNTGenerator.setMinimumSize(QtCore.QSize(400, 400))
        SWNTGenerator.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        SWNTGenerator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(SWNTGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.swnt_n_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.swnt_n_spin_box.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_n_spin_box.setFont(font)
        self.swnt_n_spin_box.setMaximum(100)
        self.swnt_n_spin_box.setProperty("value", 10)
        self.swnt_n_spin_box.setObjectName("swnt_n_spin_box")
        self.horizontalLayout_2.addWidget(self.swnt_n_spin_box)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.swnt_m_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.swnt_m_spin_box.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_m_spin_box.setFont(font)
        self.swnt_m_spin_box.setMaximum(100)
        self.swnt_m_spin_box.setProperty("value", 10)
        self.swnt_m_spin_box.setObjectName("swnt_m_spin_box")
        self.horizontalLayout.addWidget(self.swnt_m_spin_box)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_24.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.swnt_nz_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.swnt_nz_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_nz_double_spin_box.setFont(font)
        self.swnt_nz_double_spin_box.setDecimals(2)
        self.swnt_nz_double_spin_box.setMaximum(1000.0)
        self.swnt_nz_double_spin_box.setProperty("value", 1.0)
        self.swnt_nz_double_spin_box.setObjectName("swnt_nz_double_spin_box")
        self.horizontalLayout_6.addWidget(self.swnt_nz_double_spin_box)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.swnt_Lz_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_Lz_double_spin_box.sizePolicy().hasHeightForWidth())
        self.swnt_Lz_double_spin_box.setSizePolicy(sizePolicy)
        self.swnt_Lz_double_spin_box.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_Lz_double_spin_box.setFont(font)
        self.swnt_Lz_double_spin_box.setReadOnly(True)
        self.swnt_Lz_double_spin_box.setDecimals(4)
        self.swnt_Lz_double_spin_box.setMaximum(1000.0)
        self.swnt_Lz_double_spin_box.setObjectName("swnt_Lz_double_spin_box")
        self.horizontalLayout_9.addWidget(self.swnt_Lz_double_spin_box)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_9)
        self.swnt_fix_Lz_check_box = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_fix_Lz_check_box.setFont(font)
        self.swnt_fix_Lz_check_box.setCheckable(True)
        self.swnt_fix_Lz_check_box.setObjectName("swnt_fix_Lz_check_box")
        self.horizontalLayout_23.addWidget(self.swnt_fix_Lz_check_box)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_23)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem2)
        self.verticalLayout_24.addLayout(self.horizontalLayout_61)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_25.addWidget(self.line_2)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.bundle_generator_check_box = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bundle_generator_check_box.setFont(font)
        self.bundle_generator_check_box.setCheckable(True)
        self.bundle_generator_check_box.setObjectName("bundle_generator_check_box")
        self.verticalLayout_23.addWidget(self.bundle_generator_check_box)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.bundle_nx_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_nx_spin_box.sizePolicy().hasHeightForWidth())
        self.bundle_nx_spin_box.setSizePolicy(sizePolicy)
        self.bundle_nx_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bundle_nx_spin_box.setFont(font)
        self.bundle_nx_spin_box.setReadOnly(True)
        self.bundle_nx_spin_box.setMinimum(1)
        self.bundle_nx_spin_box.setObjectName("bundle_nx_spin_box")
        self.horizontalLayout_4.addWidget(self.bundle_nx_spin_box)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.bundle_Lx_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_Lx_line_edit.sizePolicy().hasHeightForWidth())
        self.bundle_Lx_line_edit.setSizePolicy(sizePolicy)
        self.bundle_Lx_line_edit.setMinimumSize(QtCore.QSize(175, 36))
        self.bundle_Lx_line_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bundle_Lx_line_edit.setFont(font)
        self.bundle_Lx_line_edit.setReadOnly(True)
        self.bundle_Lx_line_edit.setObjectName("bundle_Lx_line_edit")
        self.horizontalLayout_7.addWidget(self.bundle_Lx_line_edit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.bundle_ny_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_ny_spin_box.sizePolicy().hasHeightForWidth())
        self.bundle_ny_spin_box.setSizePolicy(sizePolicy)
        self.bundle_ny_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bundle_ny_spin_box.setFont(font)
        self.bundle_ny_spin_box.setReadOnly(True)
        self.bundle_ny_spin_box.setMinimum(1)
        self.bundle_ny_spin_box.setObjectName("bundle_ny_spin_box")
        self.horizontalLayout_5.addWidget(self.bundle_ny_spin_box)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.bundle_Ly_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_Ly_line_edit.sizePolicy().hasHeightForWidth())
        self.bundle_Ly_line_edit.setSizePolicy(sizePolicy)
        self.bundle_Ly_line_edit.setMinimumSize(QtCore.QSize(175, 36))
        self.bundle_Ly_line_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bundle_Ly_line_edit.setFont(font)
        self.bundle_Ly_line_edit.setReadOnly(True)
        self.bundle_Ly_line_edit.setObjectName("bundle_Ly_line_edit")
        self.horizontalLayout_8.addWidget(self.bundle_Ly_line_edit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_22.addLayout(self.horizontalLayout_10)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout.addLayout(self.verticalLayout_25)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.element1_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.element1_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element1_combo_box.setFont(font)
        self.element1_combo_box.setObjectName("element1_combo_box")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.horizontalLayout_29.addWidget(self.element1_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.element2_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.element2_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element2_combo_box.setFont(font)
        self.element2_combo_box.setObjectName("element2_combo_box")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.horizontalLayout_28.addWidget(self.element2_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.elements_bond_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.elements_bond_label.setFont(font)
        self.elements_bond_label.setObjectName("elements_bond_label")
        self.horizontalLayout_14.addWidget(self.elements_bond_label)
        self.bond_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bond_double_spin_box.sizePolicy().hasHeightForWidth())
        self.bond_double_spin_box.setSizePolicy(sizePolicy)
        self.bond_double_spin_box.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.bond_double_spin_box.setFont(font)
        self.bond_double_spin_box.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.bond_double_spin_box.setReadOnly(False)
        self.bond_double_spin_box.setDecimals(3)
        self.bond_double_spin_box.setMinimum(0.5)
        self.bond_double_spin_box.setMaximum(10.0)
        self.bond_double_spin_box.setSingleStep(0.01)
        self.bond_double_spin_box.setProperty("value", 1.42)
        self.bond_double_spin_box.setObjectName("bond_double_spin_box")
        self.horizontalLayout_14.addWidget(self.bond_double_spin_box)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        SWNTGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(SWNTGenerator)
        self.element1_combo_box.setCurrentIndex(3)
        self.element2_combo_box.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SWNTGenerator)

    def retranslateUi(self, SWNTGenerator):
        _translate = QtCore.QCoreApplication.translate
        SWNTGenerator.setWindowTitle(_translate("SWNTGenerator", "SWNT Generator"))
        self.label_7.setText(_translate("SWNTGenerator", "<html><head/><body><p align=\"right\">n = </p></body></html>"))
        self.label_14.setText(_translate("SWNTGenerator", "<html><head/><body><p align=\"right\">m = </p></body></html>"))
        self.label_4.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>"))
        self.label_13.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.swnt_Lz_double_spin_box.setSuffix(_translate("SWNTGenerator", " nm"))
        self.swnt_fix_Lz_check_box.setText(_translate("SWNTGenerator", "Fix Lz"))
        self.bundle_generator_check_box.setText(_translate("SWNTGenerator", "Bundle Generator"))
        self.label.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_2.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.label_3.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>"))
        self.label_12.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>"))
        self.label_17.setText(_translate("SWNTGenerator", "Element 1:"))
        self.element1_combo_box.setItemText(0, _translate("SWNTGenerator", "H"))
        self.element1_combo_box.setItemText(1, _translate("SWNTGenerator", "He"))
        self.element1_combo_box.setItemText(2, _translate("SWNTGenerator", "B"))
        self.element1_combo_box.setItemText(3, _translate("SWNTGenerator", "C"))
        self.element1_combo_box.setItemText(4, _translate("SWNTGenerator", "N"))
        self.label_18.setText(_translate("SWNTGenerator", "Element 2:"))
        self.element2_combo_box.setItemText(0, _translate("SWNTGenerator", "H"))
        self.element2_combo_box.setItemText(1, _translate("SWNTGenerator", "He"))
        self.element2_combo_box.setItemText(2, _translate("SWNTGenerator", "B"))
        self.element2_combo_box.setItemText(3, _translate("SWNTGenerator", "C"))
        self.element2_combo_box.setItemText(4, _translate("SWNTGenerator", "N"))
        self.elements_bond_label.setText(_translate("SWNTGenerator", "<html><head/><body><p>C-C bond =</p></body></html>"))
        self.bond_double_spin_box.setSuffix(_translate("SWNTGenerator", " Å"))

