# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nanogen.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NanoGen(object):
    def setupUi(self, NanoGen):
        NanoGen.setObjectName("NanoGen")
        NanoGen.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NanoGen.sizePolicy().hasHeightForWidth())
        NanoGen.setSizePolicy(sizePolicy)
        NanoGen.setMinimumSize(QtCore.QSize(500, 300))
        NanoGen.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        NanoGen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(NanoGen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.swnt_generator_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.swnt_generator_push_button.setFont(font)
        self.swnt_generator_push_button.setObjectName("swnt_generator_push_button")
        self.verticalLayout.addWidget(self.swnt_generator_push_button)
        self.mwnt_generator_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.mwnt_generator_push_button.setFont(font)
        self.mwnt_generator_push_button.setObjectName("mwnt_generator_push_button")
        self.verticalLayout.addWidget(self.mwnt_generator_push_button)
        self.graphene_generator_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graphene_generator_push_button.setFont(font)
        self.graphene_generator_push_button.setObjectName("graphene_generator_push_button")
        self.verticalLayout.addWidget(self.graphene_generator_push_button)
        self.fullerene_generator_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fullerene_generator_push_button.setFont(font)
        self.fullerene_generator_push_button.setObjectName("fullerene_generator_push_button")
        self.verticalLayout.addWidget(self.fullerene_generator_push_button)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.save_as_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.save_as_push_button.setFont(font)
        self.save_as_push_button.setObjectName("save_as_push_button")
        self.horizontalLayout_25.addWidget(self.save_as_push_button)
        self.fpath_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fpath_line_edit.setFont(font)
        self.fpath_line_edit.setObjectName("fpath_line_edit")
        self.horizontalLayout_25.addWidget(self.fpath_line_edit)
        self.structure_format_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.structure_format_combo_box.setMinimumSize(QtCore.QSize(80, 36))
        self.structure_format_combo_box.setMaximumSize(QtCore.QSize(120, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.structure_format_combo_box.setFont(font)
        self.structure_format_combo_box.setModelColumn(0)
        self.structure_format_combo_box.setObjectName("structure_format_combo_box")
        self.structure_format_combo_box.addItem("")
        self.structure_format_combo_box.addItem("")
        self.horizontalLayout_25.addWidget(self.structure_format_combo_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.generate_push_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.generate_push_button.setFont(font)
        self.generate_push_button.setObjectName("generate_push_button")
        self.horizontalLayout_15.addWidget(self.generate_push_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        NanoGen.setCentralWidget(self.centralwidget)
        self.nanogen_status_bar = QtWidgets.QStatusBar(NanoGen)
        self.nanogen_status_bar.setObjectName("nanogen_status_bar")
        NanoGen.setStatusBar(self.nanogen_status_bar)

        self.retranslateUi(NanoGen)
        self.structure_format_combo_box.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NanoGen)

    def retranslateUi(self, NanoGen):
        _translate = QtCore.QCoreApplication.translate
        NanoGen.setWindowTitle(_translate("NanoGen", "NanoGen"))
        self.swnt_generator_push_button.setText(_translate("NanoGen", "SWNT Generator"))
        self.mwnt_generator_push_button.setText(_translate("NanoGen", "MWNT Generator"))
        self.graphene_generator_push_button.setText(_translate("NanoGen", "Graphene Generator"))
        self.fullerene_generator_push_button.setText(_translate("NanoGen", "Fullerene Generator"))
        self.save_as_push_button.setText(_translate("NanoGen", "Save As..."))
        self.structure_format_combo_box.setItemText(0, _translate("NanoGen", "data"))
        self.structure_format_combo_box.setItemText(1, _translate("NanoGen", "xyz"))
        self.generate_push_button.setText(_translate("NanoGen", "Generate"))

