# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphene_generator.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GrapheneGenerator(object):
    def setupUi(self, GrapheneGenerator):
        GrapheneGenerator.setObjectName("GrapheneGenerator")
        GrapheneGenerator.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GrapheneGenerator.sizePolicy().hasHeightForWidth())
        GrapheneGenerator.setSizePolicy(sizePolicy)
        GrapheneGenerator.setMinimumSize(QtCore.QSize(600, 600))
        GrapheneGenerator.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        GrapheneGenerator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(GrapheneGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.conventional_unit_cell_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.conventional_unit_cell_radio_button.setFont(font)
        self.conventional_unit_cell_radio_button.setChecked(True)
        self.conventional_unit_cell_radio_button.setObjectName("conventional_unit_cell_radio_button")
        self.graphene_generator_button_group = QtWidgets.QButtonGroup(GrapheneGenerator)
        self.graphene_generator_button_group.setObjectName("graphene_generator_button_group")
        self.graphene_generator_button_group.addButton(self.conventional_unit_cell_radio_button)
        self.verticalLayout_15.addWidget(self.conventional_unit_cell_radio_button)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.armchair_edge_length_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.armchair_edge_length_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.armchair_edge_length_double_spin_box.setFont(font)
        self.armchair_edge_length_double_spin_box.setDecimals(4)
        self.armchair_edge_length_double_spin_box.setMinimum(0.1)
        self.armchair_edge_length_double_spin_box.setMaximum(100.0)
        self.armchair_edge_length_double_spin_box.setProperty("value", 1.0)
        self.armchair_edge_length_double_spin_box.setObjectName("armchair_edge_length_double_spin_box")
        self.horizontalLayout_16.addWidget(self.armchair_edge_length_double_spin_box)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.zigzag_edge_length_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zigzag_edge_length_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zigzag_edge_length_double_spin_box.setFont(font)
        self.zigzag_edge_length_double_spin_box.setDecimals(4)
        self.zigzag_edge_length_double_spin_box.setMinimum(0.1)
        self.zigzag_edge_length_double_spin_box.setMaximum(100.0)
        self.zigzag_edge_length_double_spin_box.setProperty("value", 1.0)
        self.zigzag_edge_length_double_spin_box.setObjectName("zigzag_edge_length_double_spin_box")
        self.horizontalLayout_17.addWidget(self.zigzag_edge_length_double_spin_box)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_17)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_2.addLayout(self.verticalLayout_15)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.primitive_unit_cell_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.primitive_unit_cell_radio_button.setFont(font)
        self.primitive_unit_cell_radio_button.setChecked(False)
        self.primitive_unit_cell_radio_button.setObjectName("primitive_unit_cell_radio_button")
        self.graphene_generator_button_group.addButton(self.primitive_unit_cell_radio_button)
        self.verticalLayout_17.addWidget(self.primitive_unit_cell_radio_button)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_25.addWidget(self.label_12)
        self.edge_length_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.edge_length_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.edge_length_double_spin_box.setFont(font)
        self.edge_length_double_spin_box.setReadOnly(True)
        self.edge_length_double_spin_box.setDecimals(4)
        self.edge_length_double_spin_box.setMinimum(0.1)
        self.edge_length_double_spin_box.setMaximum(100.0)
        self.edge_length_double_spin_box.setProperty("value", 1.0)
        self.edge_length_double_spin_box.setObjectName("edge_length_double_spin_box")
        self.horizontalLayout_25.addWidget(self.edge_length_double_spin_box)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_25)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_23)
        self.verticalLayout_17.addLayout(self.verticalLayout_19)
        self.verticalLayout_2.addLayout(self.verticalLayout_17)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.unrolled_swnt_chirality_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_chirality_radio_button.setFont(font)
        self.unrolled_swnt_chirality_radio_button.setObjectName("unrolled_swnt_chirality_radio_button")
        self.graphene_generator_button_group.addButton(self.unrolled_swnt_chirality_radio_button)
        self.verticalLayout_16.addWidget(self.unrolled_swnt_chirality_radio_button)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_53.addWidget(self.label_27)
        self.swnt_n_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.swnt_n_spin_box.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.swnt_n_spin_box.setFont(font)
        self.swnt_n_spin_box.setReadOnly(True)
        self.swnt_n_spin_box.setMaximum(100)
        self.swnt_n_spin_box.setProperty("value", 10)
        self.swnt_n_spin_box.setObjectName("swnt_n_spin_box")
        self.horizontalLayout_53.addWidget(self.swnt_n_spin_box)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_54.addWidget(self.label_28)
        self.swnt_m_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.swnt_m_spin_box.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.swnt_m_spin_box.setFont(font)
        self.swnt_m_spin_box.setReadOnly(True)
        self.swnt_m_spin_box.setMaximum(100)
        self.swnt_m_spin_box.setProperty("value", 10)
        self.swnt_m_spin_box.setObjectName("swnt_m_spin_box")
        self.horizontalLayout_54.addWidget(self.swnt_m_spin_box)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_52)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_58.addWidget(self.label_31)
        self.unrolled_swnt_nx_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_nx_spin_box.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_nx_spin_box.setSizePolicy(sizePolicy)
        self.unrolled_swnt_nx_spin_box.setMinimumSize(QtCore.QSize(80, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_nx_spin_box.setFont(font)
        self.unrolled_swnt_nx_spin_box.setReadOnly(True)
        self.unrolled_swnt_nx_spin_box.setMinimum(1)
        self.unrolled_swnt_nx_spin_box.setMaximum(1000)
        self.unrolled_swnt_nx_spin_box.setProperty("value", 1)
        self.unrolled_swnt_nx_spin_box.setObjectName("unrolled_swnt_nx_spin_box")
        self.horizontalLayout_58.addWidget(self.unrolled_swnt_nx_spin_box)
        self.horizontalLayout_57.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_59.addWidget(self.label_32)
        self.unrolled_swnt_Lx_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_Lx_double_spin_box.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_Lx_double_spin_box.setSizePolicy(sizePolicy)
        self.unrolled_swnt_Lx_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_Lx_double_spin_box.setFont(font)
        self.unrolled_swnt_Lx_double_spin_box.setReadOnly(True)
        self.unrolled_swnt_Lx_double_spin_box.setDecimals(4)
        self.unrolled_swnt_Lx_double_spin_box.setMaximum(1000.0)
        self.unrolled_swnt_Lx_double_spin_box.setObjectName("unrolled_swnt_Lx_double_spin_box")
        self.horizontalLayout_59.addWidget(self.unrolled_swnt_Lx_double_spin_box)
        self.horizontalLayout_57.addLayout(self.horizontalLayout_59)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_55.addWidget(self.label_29)
        self.unrolled_swnt_nz_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_nz_spin_box.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_nz_spin_box.setSizePolicy(sizePolicy)
        self.unrolled_swnt_nz_spin_box.setMinimumSize(QtCore.QSize(80, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_nz_spin_box.setFont(font)
        self.unrolled_swnt_nz_spin_box.setReadOnly(True)
        self.unrolled_swnt_nz_spin_box.setMinimum(1)
        self.unrolled_swnt_nz_spin_box.setMaximum(1000)
        self.unrolled_swnt_nz_spin_box.setProperty("value", 1)
        self.unrolled_swnt_nz_spin_box.setObjectName("unrolled_swnt_nz_spin_box")
        self.horizontalLayout_55.addWidget(self.unrolled_swnt_nz_spin_box)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_56.addWidget(self.label_30)
        self.unrolled_swnt_Lz_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_Lz_double_spin_box.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_Lz_double_spin_box.setSizePolicy(sizePolicy)
        self.unrolled_swnt_Lz_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_Lz_double_spin_box.setFont(font)
        self.unrolled_swnt_Lz_double_spin_box.setReadOnly(True)
        self.unrolled_swnt_Lz_double_spin_box.setDecimals(4)
        self.unrolled_swnt_Lz_double_spin_box.setMaximum(1000.0)
        self.unrolled_swnt_Lz_double_spin_box.setObjectName("unrolled_swnt_Lz_double_spin_box")
        self.horizontalLayout_56.addWidget(self.unrolled_swnt_Lz_double_spin_box)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_56)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_42)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_16)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem6)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.nlayers_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.nlayers_spin_box.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.nlayers_spin_box.setFont(font)
        self.nlayers_spin_box.setMinimum(1)
        self.nlayers_spin_box.setMaximum(50)
        self.nlayers_spin_box.setObjectName("nlayers_spin_box")
        self.horizontalLayout_18.addWidget(self.nlayers_spin_box)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_18)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.AA_stacking_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.AA_stacking_radio_button.setFont(font)
        self.AA_stacking_radio_button.setCheckable(True)
        self.AA_stacking_radio_button.setChecked(False)
        self.AA_stacking_radio_button.setObjectName("AA_stacking_radio_button")
        self.stacking_order_button_group = QtWidgets.QButtonGroup(GrapheneGenerator)
        self.stacking_order_button_group.setObjectName("stacking_order_button_group")
        self.stacking_order_button_group.addButton(self.AA_stacking_radio_button)
        self.verticalLayout_4.addWidget(self.AA_stacking_radio_button)
        self.AB_stacking_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.AB_stacking_radio_button.setFont(font)
        self.AB_stacking_radio_button.setCheckable(True)
        self.AB_stacking_radio_button.setChecked(True)
        self.AB_stacking_radio_button.setObjectName("AB_stacking_radio_button")
        self.stacking_order_button_group.addButton(self.AB_stacking_radio_button)
        self.verticalLayout_4.addWidget(self.AB_stacking_radio_button)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        self.layer_rotation_increment_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.layer_rotation_increment_double_spin_box.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.layer_rotation_increment_double_spin_box.setFont(font)
        self.layer_rotation_increment_double_spin_box.setReadOnly(True)
        self.layer_rotation_increment_double_spin_box.setMaximum(359.99)
        self.layer_rotation_increment_double_spin_box.setProperty("value", 0.0)
        self.layer_rotation_increment_double_spin_box.setObjectName("layer_rotation_increment_double_spin_box")
        self.horizontalLayout_22.addWidget(self.layer_rotation_increment_double_spin_box)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_22)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.verticalLayout_18.addLayout(self.verticalLayout_14)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem9)
        self.horizontalLayout.addLayout(self.verticalLayout_18)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.element1_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.element1_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element1_combo_box.setFont(font)
        self.element1_combo_box.setObjectName("element1_combo_box")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.element1_combo_box.addItem("")
        self.horizontalLayout_29.addWidget(self.element1_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.element2_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.element2_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element2_combo_box.setFont(font)
        self.element2_combo_box.setObjectName("element2_combo_box")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.element2_combo_box.addItem("")
        self.horizontalLayout_28.addWidget(self.element2_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.elements_bond_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.elements_bond_label.setFont(font)
        self.elements_bond_label.setObjectName("elements_bond_label")
        self.horizontalLayout_14.addWidget(self.elements_bond_label)
        self.bond_double_spin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bond_double_spin_box.sizePolicy().hasHeightForWidth())
        self.bond_double_spin_box.setSizePolicy(sizePolicy)
        self.bond_double_spin_box.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.bond_double_spin_box.setFont(font)
        self.bond_double_spin_box.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.bond_double_spin_box.setReadOnly(False)
        self.bond_double_spin_box.setDecimals(3)
        self.bond_double_spin_box.setMinimum(0.5)
        self.bond_double_spin_box.setMaximum(10.0)
        self.bond_double_spin_box.setSingleStep(0.01)
        self.bond_double_spin_box.setProperty("value", 1.42)
        self.bond_double_spin_box.setObjectName("bond_double_spin_box")
        self.horizontalLayout_14.addWidget(self.bond_double_spin_box)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem12 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        GrapheneGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(GrapheneGenerator)
        self.element1_combo_box.setCurrentIndex(3)
        self.element2_combo_box.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(GrapheneGenerator)

    def retranslateUi(self, GrapheneGenerator):
        _translate = QtCore.QCoreApplication.translate
        GrapheneGenerator.setWindowTitle(_translate("GrapheneGenerator", "Graphene Generator"))
        self.label_33.setText(_translate("GrapheneGenerator", "Generate from..."))
        self.conventional_unit_cell_radio_button.setText(_translate("GrapheneGenerator", "Conventional Unit Cell"))
        self.label_9.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">armchair</span> =</p></body></html>"))
        self.armchair_edge_length_double_spin_box.setSuffix(_translate("GrapheneGenerator", " nm"))
        self.label_10.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">zigzag</span> =</p></body></html>"))
        self.zigzag_edge_length_double_spin_box.setSuffix(_translate("GrapheneGenerator", " nm"))
        self.primitive_unit_cell_radio_button.setText(_translate("GrapheneGenerator", "Primitive Unit Cell"))
        self.label_12.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">edge</span> =</p></body></html>"))
        self.edge_length_double_spin_box.setSuffix(_translate("GrapheneGenerator", " nm"))
        self.unrolled_swnt_chirality_radio_button.setText(_translate("GrapheneGenerator", "(n, m) Chiral Indices"))
        self.label_27.setText(_translate("GrapheneGenerator", "<html><head/><body><p align=\"right\">n = </p></body></html>"))
        self.label_28.setText(_translate("GrapheneGenerator", "<html><head/><body><p align=\"right\">m = </p></body></html>"))
        self.label_31.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_32.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.unrolled_swnt_Lx_double_spin_box.setSuffix(_translate("GrapheneGenerator", " nm"))
        self.label_29.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>"))
        self.label_30.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.unrolled_swnt_Lz_double_spin_box.setSuffix(_translate("GrapheneGenerator", " nm"))
        self.label_11.setText(_translate("GrapheneGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">layers</span> =</p></body></html>"))
        self.label_6.setText(_translate("GrapheneGenerator", "<html><head/><body><p>Stacking Order</p></body></html>"))
        self.AA_stacking_radio_button.setText(_translate("GrapheneGenerator", "AA"))
        self.AB_stacking_radio_button.setText(_translate("GrapheneGenerator", "AB"))
        self.label_15.setText(_translate("GrapheneGenerator", "<html><head/><body><p>deg/layer =</p></body></html>"))
        self.label_17.setText(_translate("GrapheneGenerator", "Element 1:"))
        self.element1_combo_box.setItemText(0, _translate("GrapheneGenerator", "H"))
        self.element1_combo_box.setItemText(1, _translate("GrapheneGenerator", "He"))
        self.element1_combo_box.setItemText(2, _translate("GrapheneGenerator", "B"))
        self.element1_combo_box.setItemText(3, _translate("GrapheneGenerator", "C"))
        self.element1_combo_box.setItemText(4, _translate("GrapheneGenerator", "N"))
        self.label_18.setText(_translate("GrapheneGenerator", "Element 2:"))
        self.element2_combo_box.setItemText(0, _translate("GrapheneGenerator", "H"))
        self.element2_combo_box.setItemText(1, _translate("GrapheneGenerator", "He"))
        self.element2_combo_box.setItemText(2, _translate("GrapheneGenerator", "B"))
        self.element2_combo_box.setItemText(3, _translate("GrapheneGenerator", "C"))
        self.element2_combo_box.setItemText(4, _translate("GrapheneGenerator", "N"))
        self.elements_bond_label.setText(_translate("GrapheneGenerator", "<html><head/><body><p>C-C bond =</p></body></html>"))
        self.bond_double_spin_box.setSuffix(_translate("GrapheneGenerator", " Å"))

