# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swnt_generator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SWNTGenerator(object):
    def setupUi(self, SWNTGenerator):
        SWNTGenerator.setObjectName(_fromUtf8("SWNTGenerator"))
        SWNTGenerator.resize(427, 436)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SWNTGenerator.sizePolicy().hasHeightForWidth())
        SWNTGenerator.setSizePolicy(sizePolicy)
        SWNTGenerator.setMinimumSize(QtCore.QSize(400, 400))
        SWNTGenerator.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        SWNTGenerator.setFont(font)
        self.centralwidget = QtGui.QWidget(SWNTGenerator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.swnt_n_spin_box = QtGui.QSpinBox(self.centralwidget)
        self.swnt_n_spin_box.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.swnt_n_spin_box.setFont(font)
        self.swnt_n_spin_box.setMaximum(100)
        self.swnt_n_spin_box.setProperty("value", 10)
        self.swnt_n_spin_box.setObjectName(_fromUtf8("swnt_n_spin_box"))
        self.horizontalLayout_2.addWidget(self.swnt_n_spin_box)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.swnt_m_spin_box = QtGui.QSpinBox(self.centralwidget)
        self.swnt_m_spin_box.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.swnt_m_spin_box.setFont(font)
        self.swnt_m_spin_box.setMaximum(100)
        self.swnt_m_spin_box.setProperty("value", 10)
        self.swnt_m_spin_box.setObjectName(_fromUtf8("swnt_m_spin_box"))
        self.horizontalLayout.addWidget(self.swnt_m_spin_box)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_24.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.swnt_nz_double_spin_box = QtGui.QDoubleSpinBox(self.centralwidget)
        self.swnt_nz_double_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.swnt_nz_double_spin_box.setFont(font)
        self.swnt_nz_double_spin_box.setDecimals(2)
        self.swnt_nz_double_spin_box.setMaximum(1000.0)
        self.swnt_nz_double_spin_box.setProperty("value", 1.0)
        self.swnt_nz_double_spin_box.setObjectName(_fromUtf8("swnt_nz_double_spin_box"))
        self.horizontalLayout_6.addWidget(self.swnt_nz_double_spin_box)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.swnt_Lz_double_spin_box = QtGui.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_Lz_double_spin_box.sizePolicy().hasHeightForWidth())
        self.swnt_Lz_double_spin_box.setSizePolicy(sizePolicy)
        self.swnt_Lz_double_spin_box.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.swnt_Lz_double_spin_box.setFont(font)
        self.swnt_Lz_double_spin_box.setReadOnly(True)
        self.swnt_Lz_double_spin_box.setDecimals(4)
        self.swnt_Lz_double_spin_box.setMaximum(1000.0)
        self.swnt_Lz_double_spin_box.setObjectName(_fromUtf8("swnt_Lz_double_spin_box"))
        self.horizontalLayout_9.addWidget(self.swnt_Lz_double_spin_box)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_9)
        self.swnt_fix_Lz_check_box = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.swnt_fix_Lz_check_box.setFont(font)
        self.swnt_fix_Lz_check_box.setCheckable(True)
        self.swnt_fix_Lz_check_box.setObjectName(_fromUtf8("swnt_fix_Lz_check_box"))
        self.horizontalLayout_23.addWidget(self.swnt_fix_Lz_check_box)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_23)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem2)
        self.verticalLayout_24.addLayout(self.horizontalLayout_61)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_25.addWidget(self.line_2)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.bundle_generator_check_box = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.bundle_generator_check_box.setFont(font)
        self.bundle_generator_check_box.setCheckable(True)
        self.bundle_generator_check_box.setObjectName(_fromUtf8("bundle_generator_check_box"))
        self.verticalLayout_23.addWidget(self.bundle_generator_check_box)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.bundle_nx_spin_box = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_nx_spin_box.sizePolicy().hasHeightForWidth())
        self.bundle_nx_spin_box.setSizePolicy(sizePolicy)
        self.bundle_nx_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.bundle_nx_spin_box.setFont(font)
        self.bundle_nx_spin_box.setReadOnly(True)
        self.bundle_nx_spin_box.setMinimum(1)
        self.bundle_nx_spin_box.setObjectName(_fromUtf8("bundle_nx_spin_box"))
        self.horizontalLayout_4.addWidget(self.bundle_nx_spin_box)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.bundle_Lx_line_edit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_Lx_line_edit.sizePolicy().hasHeightForWidth())
        self.bundle_Lx_line_edit.setSizePolicy(sizePolicy)
        self.bundle_Lx_line_edit.setMinimumSize(QtCore.QSize(175, 36))
        self.bundle_Lx_line_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.bundle_Lx_line_edit.setFont(font)
        self.bundle_Lx_line_edit.setReadOnly(True)
        self.bundle_Lx_line_edit.setObjectName(_fromUtf8("bundle_Lx_line_edit"))
        self.horizontalLayout_7.addWidget(self.bundle_Lx_line_edit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.bundle_ny_spin_box = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_ny_spin_box.sizePolicy().hasHeightForWidth())
        self.bundle_ny_spin_box.setSizePolicy(sizePolicy)
        self.bundle_ny_spin_box.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.bundle_ny_spin_box.setFont(font)
        self.bundle_ny_spin_box.setReadOnly(True)
        self.bundle_ny_spin_box.setMinimum(1)
        self.bundle_ny_spin_box.setObjectName(_fromUtf8("bundle_ny_spin_box"))
        self.horizontalLayout_5.addWidget(self.bundle_ny_spin_box)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.bundle_Ly_line_edit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bundle_Ly_line_edit.sizePolicy().hasHeightForWidth())
        self.bundle_Ly_line_edit.setSizePolicy(sizePolicy)
        self.bundle_Ly_line_edit.setMinimumSize(QtCore.QSize(175, 36))
        self.bundle_Ly_line_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.bundle_Ly_line_edit.setFont(font)
        self.bundle_Ly_line_edit.setReadOnly(True)
        self.bundle_Ly_line_edit.setObjectName(_fromUtf8("bundle_Ly_line_edit"))
        self.horizontalLayout_8.addWidget(self.bundle_Ly_line_edit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_22.addLayout(self.horizontalLayout_10)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout.addLayout(self.verticalLayout_25)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_29.addWidget(self.label_17)
        self.element1_combo_box = QtGui.QComboBox(self.centralwidget)
        self.element1_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.element1_combo_box.setFont(font)
        self.element1_combo_box.setObjectName(_fromUtf8("element1_combo_box"))
        self.element1_combo_box.addItem(_fromUtf8(""))
        self.element1_combo_box.addItem(_fromUtf8(""))
        self.element1_combo_box.addItem(_fromUtf8(""))
        self.element1_combo_box.addItem(_fromUtf8(""))
        self.element1_combo_box.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.element1_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_28.addWidget(self.label_18)
        self.element2_combo_box = QtGui.QComboBox(self.centralwidget)
        self.element2_combo_box.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.element2_combo_box.setFont(font)
        self.element2_combo_box.setObjectName(_fromUtf8("element2_combo_box"))
        self.element2_combo_box.addItem(_fromUtf8(""))
        self.element2_combo_box.addItem(_fromUtf8(""))
        self.element2_combo_box.addItem(_fromUtf8(""))
        self.element2_combo_box.addItem(_fromUtf8(""))
        self.element2_combo_box.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.element2_combo_box)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.elements_bond_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.elements_bond_label.setFont(font)
        self.elements_bond_label.setObjectName(_fromUtf8("elements_bond_label"))
        self.horizontalLayout_14.addWidget(self.elements_bond_label)
        self.bond_double_spin_box = QtGui.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bond_double_spin_box.sizePolicy().hasHeightForWidth())
        self.bond_double_spin_box.setSizePolicy(sizePolicy)
        self.bond_double_spin_box.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.bond_double_spin_box.setFont(font)
        self.bond_double_spin_box.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.bond_double_spin_box.setReadOnly(False)
        self.bond_double_spin_box.setDecimals(3)
        self.bond_double_spin_box.setMinimum(0.5)
        self.bond_double_spin_box.setMaximum(10.0)
        self.bond_double_spin_box.setSingleStep(0.01)
        self.bond_double_spin_box.setProperty("value", 1.42)
        self.bond_double_spin_box.setObjectName(_fromUtf8("bond_double_spin_box"))
        self.horizontalLayout_14.addWidget(self.bond_double_spin_box)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(20, 75, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        SWNTGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(SWNTGenerator)
        self.element1_combo_box.setCurrentIndex(3)
        self.element2_combo_box.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SWNTGenerator)

    def retranslateUi(self, SWNTGenerator):
        SWNTGenerator.setWindowTitle(_translate("SWNTGenerator", "SWNT Generator", None))
        self.label_7.setText(_translate("SWNTGenerator", "<html><head/><body><p align=\"right\">n = </p></body></html>", None))
        self.label_14.setText(_translate("SWNTGenerator", "<html><head/><body><p align=\"right\">m = </p></body></html>", None))
        self.label_4.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>", None))
        self.label_13.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>", None))
        self.swnt_Lz_double_spin_box.setSuffix(_translate("SWNTGenerator", " nm", None))
        self.swnt_fix_Lz_check_box.setText(_translate("SWNTGenerator", "Fix Lz", None))
        self.bundle_generator_check_box.setText(_translate("SWNTGenerator", "Bundle Generator", None))
        self.label.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>", None))
        self.label_2.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>", None))
        self.label_3.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>", None))
        self.label_12.setText(_translate("SWNTGenerator", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>", None))
        self.label_17.setText(_translate("SWNTGenerator", "Element 1:", None))
        self.element1_combo_box.setItemText(0, _translate("SWNTGenerator", "H", None))
        self.element1_combo_box.setItemText(1, _translate("SWNTGenerator", "He", None))
        self.element1_combo_box.setItemText(2, _translate("SWNTGenerator", "B", None))
        self.element1_combo_box.setItemText(3, _translate("SWNTGenerator", "C", None))
        self.element1_combo_box.setItemText(4, _translate("SWNTGenerator", "N", None))
        self.label_18.setText(_translate("SWNTGenerator", "Element 2:", None))
        self.element2_combo_box.setItemText(0, _translate("SWNTGenerator", "H", None))
        self.element2_combo_box.setItemText(1, _translate("SWNTGenerator", "He", None))
        self.element2_combo_box.setItemText(2, _translate("SWNTGenerator", "B", None))
        self.element2_combo_box.setItemText(3, _translate("SWNTGenerator", "C", None))
        self.element2_combo_box.setItemText(4, _translate("SWNTGenerator", "N", None))
        self.elements_bond_label.setText(_translate("SWNTGenerator", "<html><head/><body><p>C-C bond =</p></body></html>", None))
        self.bond_double_spin_box.setSuffix(_translate("SWNTGenerator", " Å", None))

