# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nanogen.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NanoGen(object):
    def setupUi(self, NanoGen):
        NanoGen.setObjectName("NanoGen")
        NanoGen.resize(600, 701)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NanoGen.sizePolicy().hasHeightForWidth())
        NanoGen.setSizePolicy(sizePolicy)
        NanoGen.setMinimumSize(QtCore.QSize(600, 700))
        NanoGen.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        NanoGen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(NanoGen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.nanogen_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanogen_tabWidget.sizePolicy().hasHeightForWidth())
        self.nanogen_tabWidget.setSizePolicy(sizePolicy)
        self.nanogen_tabWidget.setMinimumSize(QtCore.QSize(600, 450))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.nanogen_tabWidget.setFont(font)
        self.nanogen_tabWidget.setObjectName("nanogen_tabWidget")
        self.swnt_generator_tab = QtWidgets.QWidget()
        self.swnt_generator_tab.setObjectName("swnt_generator_tab")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.swnt_generator_tab)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.swnt_n_spinBox = QtWidgets.QSpinBox(self.swnt_generator_tab)
        self.swnt_n_spinBox.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.swnt_n_spinBox.setFont(font)
        self.swnt_n_spinBox.setMaximum(100)
        self.swnt_n_spinBox.setProperty("value", 10)
        self.swnt_n_spinBox.setObjectName("swnt_n_spinBox")
        self.horizontalLayout_2.addWidget(self.swnt_n_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.swnt_m_spinBox = QtWidgets.QSpinBox(self.swnt_generator_tab)
        self.swnt_m_spinBox.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.swnt_m_spinBox.setFont(font)
        self.swnt_m_spinBox.setMaximum(100)
        self.swnt_m_spinBox.setProperty("value", 10)
        self.swnt_m_spinBox.setObjectName("swnt_m_spinBox")
        self.horizontalLayout.addWidget(self.swnt_m_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_24.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.swnt_nz_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.swnt_generator_tab)
        self.swnt_nz_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        self.swnt_nz_doubleSpinBox.setDecimals(2)
        self.swnt_nz_doubleSpinBox.setMaximum(1000.0)
        self.swnt_nz_doubleSpinBox.setProperty("value", 1.0)
        self.swnt_nz_doubleSpinBox.setObjectName("swnt_nz_doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.swnt_nz_doubleSpinBox)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.swnt_Lz_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.swnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_Lz_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.swnt_Lz_doubleSpinBox.setSizePolicy(sizePolicy)
        self.swnt_Lz_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.swnt_Lz_doubleSpinBox.setFont(font)
        self.swnt_Lz_doubleSpinBox.setDecimals(4)
        self.swnt_Lz_doubleSpinBox.setMaximum(1000.0)
        self.swnt_Lz_doubleSpinBox.setObjectName("swnt_Lz_doubleSpinBox")
        self.horizontalLayout_9.addWidget(self.swnt_Lz_doubleSpinBox)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_9)
        self.swnt_fix_Lz_checkBox = QtWidgets.QCheckBox(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.swnt_fix_Lz_checkBox.setFont(font)
        self.swnt_fix_Lz_checkBox.setCheckable(True)
        self.swnt_fix_Lz_checkBox.setObjectName("swnt_fix_Lz_checkBox")
        self.horizontalLayout_23.addWidget(self.swnt_fix_Lz_checkBox)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_23)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem2)
        self.verticalLayout_24.addLayout(self.horizontalLayout_61)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.line_2 = QtWidgets.QFrame(self.swnt_generator_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_25.addWidget(self.line_2)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.swnt_bundle_generator_checkBox = QtWidgets.QCheckBox(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.swnt_bundle_generator_checkBox.setFont(font)
        self.swnt_bundle_generator_checkBox.setCheckable(True)
        self.swnt_bundle_generator_checkBox.setObjectName("swnt_bundle_generator_checkBox")
        self.verticalLayout_23.addWidget(self.swnt_bundle_generator_checkBox)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.swnt_bundle_nx_spinBox = QtWidgets.QSpinBox(self.swnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_bundle_nx_spinBox.sizePolicy().hasHeightForWidth())
        self.swnt_bundle_nx_spinBox.setSizePolicy(sizePolicy)
        self.swnt_bundle_nx_spinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.swnt_bundle_nx_spinBox.setFont(font)
        self.swnt_bundle_nx_spinBox.setMinimum(1)
        self.swnt_bundle_nx_spinBox.setObjectName("swnt_bundle_nx_spinBox")
        self.horizontalLayout_4.addWidget(self.swnt_bundle_nx_spinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.swnt_bundle_Lx_lineEdit = QtWidgets.QLineEdit(self.swnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_bundle_Lx_lineEdit.sizePolicy().hasHeightForWidth())
        self.swnt_bundle_Lx_lineEdit.setSizePolicy(sizePolicy)
        self.swnt_bundle_Lx_lineEdit.setMinimumSize(QtCore.QSize(175, 36))
        self.swnt_bundle_Lx_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.swnt_bundle_Lx_lineEdit.setReadOnly(True)
        self.swnt_bundle_Lx_lineEdit.setObjectName("swnt_bundle_Lx_lineEdit")
        self.horizontalLayout_7.addWidget(self.swnt_bundle_Lx_lineEdit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.swnt_bundle_ny_spinBox = QtWidgets.QSpinBox(self.swnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_bundle_ny_spinBox.sizePolicy().hasHeightForWidth())
        self.swnt_bundle_ny_spinBox.setSizePolicy(sizePolicy)
        self.swnt_bundle_ny_spinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.swnt_bundle_ny_spinBox.setFont(font)
        self.swnt_bundle_ny_spinBox.setMinimum(1)
        self.swnt_bundle_ny_spinBox.setObjectName("swnt_bundle_ny_spinBox")
        self.horizontalLayout_5.addWidget(self.swnt_bundle_ny_spinBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.swnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.swnt_bundle_Ly_lineEdit = QtWidgets.QLineEdit(self.swnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swnt_bundle_Ly_lineEdit.sizePolicy().hasHeightForWidth())
        self.swnt_bundle_Ly_lineEdit.setSizePolicy(sizePolicy)
        self.swnt_bundle_Ly_lineEdit.setMinimumSize(QtCore.QSize(175, 36))
        self.swnt_bundle_Ly_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.swnt_bundle_Ly_lineEdit.setReadOnly(True)
        self.swnt_bundle_Ly_lineEdit.setObjectName("swnt_bundle_Ly_lineEdit")
        self.horizontalLayout_8.addWidget(self.swnt_bundle_Ly_lineEdit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_22.addLayout(self.horizontalLayout_10)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout_26.addLayout(self.verticalLayout_25)
        spacerItem5 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem5)
        self.nanogen_tabWidget.addTab(self.swnt_generator_tab, "")
        self.mwnt_generator_tab = QtWidgets.QWidget()
        self.mwnt_generator_tab.setObjectName("mwnt_generator_tab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.mwnt_generator_tab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mwnt_Ch_list_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mwnt_Ch_list_radioButton.setFont(font)
        self.mwnt_Ch_list_radioButton.setChecked(True)
        self.mwnt_Ch_list_radioButton.setObjectName("mwnt_Ch_list_radioButton")
        self.verticalLayout_3.addWidget(self.mwnt_Ch_list_radioButton)
        self.mwnt_Ch_listWidget = QtWidgets.QListWidget(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mwnt_Ch_listWidget.setFont(font)
        self.mwnt_Ch_listWidget.setObjectName("mwnt_Ch_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.mwnt_Ch_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mwnt_Ch_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.mwnt_Ch_listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.mwnt_Ch_listWidget)
        self.horizontalLayout_50.addLayout(self.verticalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.mwnt_generator_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_50.addWidget(self.line_4)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mwnt_wall_parameters_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mwnt_wall_parameters_radioButton.setFont(font)
        self.mwnt_wall_parameters_radioButton.setObjectName("mwnt_wall_parameters_radioButton")
        self.verticalLayout_9.addWidget(self.mwnt_wall_parameters_radioButton)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_24 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_47.addWidget(self.label_24)
        self.Nwalls_spinBox = QtWidgets.QSpinBox(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Nwalls_spinBox.setFont(font)
        self.Nwalls_spinBox.setMinimum(1)
        self.Nwalls_spinBox.setProperty("value", 3)
        self.Nwalls_spinBox.setObjectName("Nwalls_spinBox")
        self.horizontalLayout_47.addWidget(self.Nwalls_spinBox)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_47)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_25 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_44.addWidget(self.label_25)
        self.min_wall_diameter_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_wall_diameter_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.min_wall_diameter_doubleSpinBox.setSizePolicy(sizePolicy)
        self.min_wall_diameter_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        self.min_wall_diameter_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.min_wall_diameter_doubleSpinBox.setFont(font)
        self.min_wall_diameter_doubleSpinBox.setDecimals(1)
        self.min_wall_diameter_doubleSpinBox.setMinimum(0.0)
        self.min_wall_diameter_doubleSpinBox.setMaximum(1000.0)
        self.min_wall_diameter_doubleSpinBox.setProperty("value", 0.0)
        self.min_wall_diameter_doubleSpinBox.setObjectName("min_wall_diameter_doubleSpinBox")
        self.horizontalLayout_44.addWidget(self.min_wall_diameter_doubleSpinBox)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_44)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_23 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_41.addWidget(self.label_23)
        self.max_wall_diameter_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_wall_diameter_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.max_wall_diameter_doubleSpinBox.setSizePolicy(sizePolicy)
        self.max_wall_diameter_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        self.max_wall_diameter_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_wall_diameter_doubleSpinBox.setFont(font)
        self.max_wall_diameter_doubleSpinBox.setDecimals(1)
        self.max_wall_diameter_doubleSpinBox.setMinimum(0.1)
        self.max_wall_diameter_doubleSpinBox.setMaximum(9999.9)
        self.max_wall_diameter_doubleSpinBox.setProperty("value", 100.0)
        self.max_wall_diameter_doubleSpinBox.setObjectName("max_wall_diameter_doubleSpinBox")
        self.horizontalLayout_41.addWidget(self.max_wall_diameter_doubleSpinBox)
        self.horizontalLayout_40.addLayout(self.horizontalLayout_41)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_26 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_46.addWidget(self.label_26)
        self.wall_spacing_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wall_spacing_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.wall_spacing_doubleSpinBox.setSizePolicy(sizePolicy)
        self.wall_spacing_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        self.wall_spacing_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wall_spacing_doubleSpinBox.setFont(font)
        self.wall_spacing_doubleSpinBox.setDecimals(2)
        self.wall_spacing_doubleSpinBox.setMinimum(0.1)
        self.wall_spacing_doubleSpinBox.setMaximum(100.0)
        self.wall_spacing_doubleSpinBox.setProperty("value", 3.35)
        self.wall_spacing_doubleSpinBox.setObjectName("wall_spacing_doubleSpinBox")
        self.horizontalLayout_46.addWidget(self.wall_spacing_doubleSpinBox)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_46)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_45)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.horizontalLayout_49.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.random_wall_chiralities_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.random_wall_chiralities_radioButton.setFont(font)
        self.random_wall_chiralities_radioButton.setChecked(True)
        self.random_wall_chiralities_radioButton.setObjectName("random_wall_chiralities_radioButton")
        self.mwnts_wall_chiral_type_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.mwnts_wall_chiral_type_buttonGroup.setObjectName("mwnts_wall_chiral_type_buttonGroup")
        self.mwnts_wall_chiral_type_buttonGroup.addButton(self.random_wall_chiralities_radioButton)
        self.verticalLayout_6.addWidget(self.random_wall_chiralities_radioButton)
        self.armchair_wall_chiralities_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.armchair_wall_chiralities_radioButton.setFont(font)
        self.armchair_wall_chiralities_radioButton.setObjectName("armchair_wall_chiralities_radioButton")
        self.mwnts_wall_chiral_type_buttonGroup.addButton(self.armchair_wall_chiralities_radioButton)
        self.verticalLayout_6.addWidget(self.armchair_wall_chiralities_radioButton)
        self.zigzag_wall_chiralities_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zigzag_wall_chiralities_radioButton.setFont(font)
        self.zigzag_wall_chiralities_radioButton.setObjectName("zigzag_wall_chiralities_radioButton")
        self.mwnts_wall_chiral_type_buttonGroup.addButton(self.zigzag_wall_chiralities_radioButton)
        self.verticalLayout_6.addWidget(self.zigzag_wall_chiralities_radioButton)
        self.achiral_wall_chiralities_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.achiral_wall_chiralities_radioButton.setFont(font)
        self.achiral_wall_chiralities_radioButton.setObjectName("achiral_wall_chiralities_radioButton")
        self.mwnts_wall_chiral_type_buttonGroup.addButton(self.achiral_wall_chiralities_radioButton)
        self.verticalLayout_6.addWidget(self.achiral_wall_chiralities_radioButton)
        self.chiral_wall_chiralities_radioButton = QtWidgets.QRadioButton(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chiral_wall_chiralities_radioButton.setFont(font)
        self.chiral_wall_chiralities_radioButton.setObjectName("chiral_wall_chiralities_radioButton")
        self.mwnts_wall_chiral_type_buttonGroup.addButton(self.chiral_wall_chiralities_radioButton)
        self.verticalLayout_6.addWidget(self.chiral_wall_chiralities_radioButton)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_49.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_50)
        self.verticalLayout_21.addLayout(self.verticalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_20 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_36.addWidget(self.label_20)
        self.mwnt_Lz_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwnt_Lz_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.mwnt_Lz_doubleSpinBox.setSizePolicy(sizePolicy)
        self.mwnt_Lz_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 36))
        self.mwnt_Lz_doubleSpinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mwnt_Lz_doubleSpinBox.setFont(font)
        self.mwnt_Lz_doubleSpinBox.setDecimals(4)
        self.mwnt_Lz_doubleSpinBox.setMinimum(0.1)
        self.mwnt_Lz_doubleSpinBox.setMaximum(100.0)
        self.mwnt_Lz_doubleSpinBox.setProperty("value", 1.0)
        self.mwnt_Lz_doubleSpinBox.setObjectName("mwnt_Lz_doubleSpinBox")
        self.horizontalLayout_36.addWidget(self.mwnt_Lz_doubleSpinBox)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_36)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem12)
        self.verticalLayout_20.addLayout(self.horizontalLayout_34)
        self.mwnt_bundle_generator_checkBox = QtWidgets.QCheckBox(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.mwnt_bundle_generator_checkBox.setFont(font)
        self.mwnt_bundle_generator_checkBox.setCheckable(True)
        self.mwnt_bundle_generator_checkBox.setObjectName("mwnt_bundle_generator_checkBox")
        self.verticalLayout_20.addWidget(self.mwnt_bundle_generator_checkBox)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_8 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_32.addWidget(self.label_8)
        self.mwnt_bundle_nx_spinBox = QtWidgets.QSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwnt_bundle_nx_spinBox.sizePolicy().hasHeightForWidth())
        self.mwnt_bundle_nx_spinBox.setSizePolicy(sizePolicy)
        self.mwnt_bundle_nx_spinBox.setMinimumSize(QtCore.QSize(60, 36))
        self.mwnt_bundle_nx_spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mwnt_bundle_nx_spinBox.setFont(font)
        self.mwnt_bundle_nx_spinBox.setMinimum(1)
        self.mwnt_bundle_nx_spinBox.setObjectName("mwnt_bundle_nx_spinBox")
        self.horizontalLayout_32.addWidget(self.mwnt_bundle_nx_spinBox)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_16 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_33.addWidget(self.label_16)
        self.mwnt_bundle_Lx_lineEdit = QtWidgets.QLineEdit(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwnt_bundle_Lx_lineEdit.sizePolicy().hasHeightForWidth())
        self.mwnt_bundle_Lx_lineEdit.setSizePolicy(sizePolicy)
        self.mwnt_bundle_Lx_lineEdit.setMinimumSize(QtCore.QSize(125, 36))
        self.mwnt_bundle_Lx_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mwnt_bundle_Lx_lineEdit.setFont(font)
        self.mwnt_bundle_Lx_lineEdit.setReadOnly(True)
        self.mwnt_bundle_Lx_lineEdit.setObjectName("mwnt_bundle_Lx_lineEdit")
        self.horizontalLayout_33.addWidget(self.mwnt_bundle_Lx_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_33)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_21 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_38.addWidget(self.label_21)
        self.mwnt_bundle_ny_spinBox = QtWidgets.QSpinBox(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwnt_bundle_ny_spinBox.sizePolicy().hasHeightForWidth())
        self.mwnt_bundle_ny_spinBox.setSizePolicy(sizePolicy)
        self.mwnt_bundle_ny_spinBox.setMinimumSize(QtCore.QSize(60, 36))
        self.mwnt_bundle_ny_spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mwnt_bundle_ny_spinBox.setFont(font)
        self.mwnt_bundle_ny_spinBox.setMinimum(1)
        self.mwnt_bundle_ny_spinBox.setObjectName("mwnt_bundle_ny_spinBox")
        self.horizontalLayout_38.addWidget(self.mwnt_bundle_ny_spinBox)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_22 = QtWidgets.QLabel(self.mwnt_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_39.addWidget(self.label_22)
        self.mwnt_bundle_Ly_lineEdit = QtWidgets.QLineEdit(self.mwnt_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwnt_bundle_Ly_lineEdit.sizePolicy().hasHeightForWidth())
        self.mwnt_bundle_Ly_lineEdit.setSizePolicy(sizePolicy)
        self.mwnt_bundle_Ly_lineEdit.setMinimumSize(QtCore.QSize(125, 36))
        self.mwnt_bundle_Ly_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mwnt_bundle_Ly_lineEdit.setFont(font)
        self.mwnt_bundle_Ly_lineEdit.setReadOnly(True)
        self.mwnt_bundle_Ly_lineEdit.setObjectName("mwnt_bundle_Ly_lineEdit")
        self.horizontalLayout_39.addWidget(self.mwnt_bundle_Ly_lineEdit)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_39)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem14)
        self.verticalLayout_19.addLayout(self.horizontalLayout_37)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.horizontalLayout_12.addLayout(self.verticalLayout_20)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_21.addLayout(self.horizontalLayout_12)
        self.nanogen_tabWidget.addTab(self.mwnt_generator_tab, "")
        self.graphene_generator_tab = QtWidgets.QWidget()
        self.graphene_generator_tab.setObjectName("graphene_generator_tab")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.graphene_generator_tab)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_33 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_17.addWidget(self.label_33)
        self.line_10 = QtWidgets.QFrame(self.graphene_generator_tab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_17.addWidget(self.line_10)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.achiral_edge_lengths_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.achiral_edge_lengths_radioButton.setFont(font)
        self.achiral_edge_lengths_radioButton.setChecked(True)
        self.achiral_edge_lengths_radioButton.setObjectName("achiral_edge_lengths_radioButton")
        self.graphene_generator_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.graphene_generator_buttonGroup.setObjectName("graphene_generator_buttonGroup")
        self.graphene_generator_buttonGroup.addButton(self.achiral_edge_lengths_radioButton)
        self.verticalLayout_15.addWidget(self.achiral_edge_lengths_radioButton)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.armchair_edge_length_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tab)
        self.armchair_edge_length_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.armchair_edge_length_doubleSpinBox.setFont(font)
        self.armchair_edge_length_doubleSpinBox.setDecimals(4)
        self.armchair_edge_length_doubleSpinBox.setMinimum(0.1)
        self.armchair_edge_length_doubleSpinBox.setMaximum(100.0)
        self.armchair_edge_length_doubleSpinBox.setProperty("value", 1.0)
        self.armchair_edge_length_doubleSpinBox.setObjectName("armchair_edge_length_doubleSpinBox")
        self.horizontalLayout_16.addWidget(self.armchair_edge_length_doubleSpinBox)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem16)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.zigzag_edge_length_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tab)
        self.zigzag_edge_length_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zigzag_edge_length_doubleSpinBox.setFont(font)
        self.zigzag_edge_length_doubleSpinBox.setDecimals(4)
        self.zigzag_edge_length_doubleSpinBox.setMinimum(0.1)
        self.zigzag_edge_length_doubleSpinBox.setMaximum(100.0)
        self.zigzag_edge_length_doubleSpinBox.setProperty("value", 1.0)
        self.zigzag_edge_length_doubleSpinBox.setObjectName("zigzag_edge_length_doubleSpinBox")
        self.horizontalLayout_17.addWidget(self.zigzag_edge_length_doubleSpinBox)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_17)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.line_7 = QtWidgets.QFrame(self.graphene_generator_tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_17.addWidget(self.line_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.unrolled_swnt_chirality_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unrolled_swnt_chirality_radioButton.setFont(font)
        self.unrolled_swnt_chirality_radioButton.setObjectName("unrolled_swnt_chirality_radioButton")
        self.graphene_generator_buttonGroup.addButton(self.unrolled_swnt_chirality_radioButton)
        self.verticalLayout_16.addWidget(self.unrolled_swnt_chirality_radioButton)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_27 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_53.addWidget(self.label_27)
        self.unrolled_swnt_n_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tab)
        self.unrolled_swnt_n_spinBox.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_n_spinBox.setFont(font)
        self.unrolled_swnt_n_spinBox.setMaximum(100)
        self.unrolled_swnt_n_spinBox.setProperty("value", 10)
        self.unrolled_swnt_n_spinBox.setObjectName("unrolled_swnt_n_spinBox")
        self.horizontalLayout_53.addWidget(self.unrolled_swnt_n_spinBox)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_28 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_54.addWidget(self.label_28)
        self.unrolled_swnt_m_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tab)
        self.unrolled_swnt_m_spinBox.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.unrolled_swnt_m_spinBox.setFont(font)
        self.unrolled_swnt_m_spinBox.setMaximum(100)
        self.unrolled_swnt_m_spinBox.setProperty("value", 10)
        self.unrolled_swnt_m_spinBox.setObjectName("unrolled_swnt_m_spinBox")
        self.horizontalLayout_54.addWidget(self.unrolled_swnt_m_spinBox)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_52)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem18)
        self.verticalLayout_12.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_31 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_58.addWidget(self.label_31)
        self.unrolled_swnt_nx_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_nx_spinBox.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_nx_spinBox.setSizePolicy(sizePolicy)
        self.unrolled_swnt_nx_spinBox.setMinimumSize(QtCore.QSize(80, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unrolled_swnt_nx_spinBox.setFont(font)
        self.unrolled_swnt_nx_spinBox.setMinimum(1)
        self.unrolled_swnt_nx_spinBox.setMaximum(1000)
        self.unrolled_swnt_nx_spinBox.setProperty("value", 1)
        self.unrolled_swnt_nx_spinBox.setObjectName("unrolled_swnt_nx_spinBox")
        self.horizontalLayout_58.addWidget(self.unrolled_swnt_nx_spinBox)
        self.horizontalLayout_57.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_32 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_59.addWidget(self.label_32)
        self.unrolled_swnt_Lx_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_Lx_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_Lx_doubleSpinBox.setSizePolicy(sizePolicy)
        self.unrolled_swnt_Lx_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unrolled_swnt_Lx_doubleSpinBox.setFont(font)
        self.unrolled_swnt_Lx_doubleSpinBox.setDecimals(4)
        self.unrolled_swnt_Lx_doubleSpinBox.setMaximum(1000.0)
        self.unrolled_swnt_Lx_doubleSpinBox.setObjectName("unrolled_swnt_Lx_doubleSpinBox")
        self.horizontalLayout_59.addWidget(self.unrolled_swnt_Lx_doubleSpinBox)
        self.horizontalLayout_57.addLayout(self.horizontalLayout_59)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem19)
        self.verticalLayout_12.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_29 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_55.addWidget(self.label_29)
        self.unrolled_swnt_nz_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_nz_spinBox.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_nz_spinBox.setSizePolicy(sizePolicy)
        self.unrolled_swnt_nz_spinBox.setMinimumSize(QtCore.QSize(80, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unrolled_swnt_nz_spinBox.setFont(font)
        self.unrolled_swnt_nz_spinBox.setMinimum(1)
        self.unrolled_swnt_nz_spinBox.setMaximum(1000)
        self.unrolled_swnt_nz_spinBox.setProperty("value", 1)
        self.unrolled_swnt_nz_spinBox.setObjectName("unrolled_swnt_nz_spinBox")
        self.horizontalLayout_55.addWidget(self.unrolled_swnt_nz_spinBox)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_30 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_56.addWidget(self.label_30)
        self.unrolled_swnt_Lz_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unrolled_swnt_Lz_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.unrolled_swnt_Lz_doubleSpinBox.setSizePolicy(sizePolicy)
        self.unrolled_swnt_Lz_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.unrolled_swnt_Lz_doubleSpinBox.setFont(font)
        self.unrolled_swnt_Lz_doubleSpinBox.setDecimals(4)
        self.unrolled_swnt_Lz_doubleSpinBox.setMaximum(1000.0)
        self.unrolled_swnt_Lz_doubleSpinBox.setObjectName("unrolled_swnt_Lz_doubleSpinBox")
        self.horizontalLayout_56.addWidget(self.unrolled_swnt_Lz_doubleSpinBox)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_56)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem20)
        self.verticalLayout_12.addLayout(self.horizontalLayout_42)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout_60.addLayout(self.verticalLayout_17)
        self.line = QtWidgets.QFrame(self.graphene_generator_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_60.addWidget(self.line)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem21)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.nlayers_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tab)
        self.nlayers_spinBox.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nlayers_spinBox.setFont(font)
        self.nlayers_spinBox.setMinimum(1)
        self.nlayers_spinBox.setMaximum(50)
        self.nlayers_spinBox.setObjectName("nlayers_spinBox")
        self.horizontalLayout_18.addWidget(self.nlayers_spinBox)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_18)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.AA_stacking_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AA_stacking_radioButton.setFont(font)
        self.AA_stacking_radioButton.setCheckable(True)
        self.AA_stacking_radioButton.setChecked(False)
        self.AA_stacking_radioButton.setObjectName("AA_stacking_radioButton")
        self.graphene_stacking_order_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.graphene_stacking_order_buttonGroup.setObjectName("graphene_stacking_order_buttonGroup")
        self.graphene_stacking_order_buttonGroup.addButton(self.AA_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AA_stacking_radioButton)
        self.AB_stacking_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AB_stacking_radioButton.setFont(font)
        self.AB_stacking_radioButton.setCheckable(True)
        self.AB_stacking_radioButton.setChecked(True)
        self.AB_stacking_radioButton.setObjectName("AB_stacking_radioButton")
        self.graphene_stacking_order_buttonGroup.addButton(self.AB_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AB_stacking_radioButton)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.graphene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        self.layer_rotation_increment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tab)
        self.layer_rotation_increment_doubleSpinBox.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.layer_rotation_increment_doubleSpinBox.setFont(font)
        self.layer_rotation_increment_doubleSpinBox.setMaximum(359.99)
        self.layer_rotation_increment_doubleSpinBox.setProperty("value", 0.0)
        self.layer_rotation_increment_doubleSpinBox.setObjectName("layer_rotation_increment_doubleSpinBox")
        self.horizontalLayout_22.addWidget(self.layer_rotation_increment_doubleSpinBox)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_22)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.verticalLayout_18.addLayout(self.verticalLayout_14)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem24)
        self.horizontalLayout_60.addLayout(self.verticalLayout_18)
        self.verticalLayout_27.addLayout(self.horizontalLayout_60)
        self.line_6 = QtWidgets.QFrame(self.graphene_generator_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_27.addWidget(self.line_6)
        spacerItem25 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem25)
        self.nanogen_tabWidget.addTab(self.graphene_generator_tab, "")
        self.fullerene_generator_tab = QtWidgets.QWidget()
        self.fullerene_generator_tab.setObjectName("fullerene_generator_tab")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.fullerene_generator_tab)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.fullerene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.fullerene_listWidget = QtWidgets.QListWidget(self.fullerene_generator_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fullerene_listWidget.setFont(font)
        self.fullerene_listWidget.setObjectName("fullerene_listWidget")
        self.verticalLayout_11.addWidget(self.fullerene_listWidget)
        self.horizontalLayout_62.addLayout(self.verticalLayout_11)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem26)
        self.verticalLayout_28.addLayout(self.horizontalLayout_62)
        self.nanogen_tabWidget.addTab(self.fullerene_generator_tab, "")
        self.verticalLayout_29.addWidget(self.nanogen_tabWidget)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_29.addWidget(self.line_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.element1_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.element1_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element1_comboBox.setFont(font)
        self.element1_comboBox.setObjectName("element1_comboBox")
        self.element1_comboBox.addItem("")
        self.element1_comboBox.addItem("")
        self.element1_comboBox.addItem("")
        self.element1_comboBox.addItem("")
        self.element1_comboBox.addItem("")
        self.horizontalLayout_29.addWidget(self.element1_comboBox)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.element2_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.element2_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.element2_comboBox.setFont(font)
        self.element2_comboBox.setObjectName("element2_comboBox")
        self.element2_comboBox.addItem("")
        self.element2_comboBox.addItem("")
        self.element2_comboBox.addItem("")
        self.element2_comboBox.addItem("")
        self.element2_comboBox.addItem("")
        self.horizontalLayout_28.addWidget(self.element2_comboBox)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem27)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.elements_bond_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.elements_bond_label.setFont(font)
        self.elements_bond_label.setObjectName("elements_bond_label")
        self.horizontalLayout_14.addWidget(self.elements_bond_label)
        self.bond_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bond_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.bond_doubleSpinBox.setSizePolicy(sizePolicy)
        self.bond_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.bond_doubleSpinBox.setFont(font)
        self.bond_doubleSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.bond_doubleSpinBox.setReadOnly(False)
        self.bond_doubleSpinBox.setDecimals(3)
        self.bond_doubleSpinBox.setMinimum(0.5)
        self.bond_doubleSpinBox.setMaximum(10.0)
        self.bond_doubleSpinBox.setSingleStep(0.01)
        self.bond_doubleSpinBox.setProperty("value", 1.42)
        self.bond_doubleSpinBox.setObjectName("bond_doubleSpinBox")
        self.horizontalLayout_14.addWidget(self.bond_doubleSpinBox)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem28)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.verticalLayout_29.addLayout(self.verticalLayout_5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_29.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.save_as_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.save_as_pushButton.setFont(font)
        self.save_as_pushButton.setObjectName("save_as_pushButton")
        self.horizontalLayout_25.addWidget(self.save_as_pushButton)
        self.fpath_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fpath_lineEdit.setFont(font)
        self.fpath_lineEdit.setObjectName("fpath_lineEdit")
        self.horizontalLayout_25.addWidget(self.fpath_lineEdit)
        self.structure_format_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.structure_format_comboBox.setMinimumSize(QtCore.QSize(80, 36))
        self.structure_format_comboBox.setMaximumSize(QtCore.QSize(120, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.structure_format_comboBox.setFont(font)
        self.structure_format_comboBox.setModelColumn(0)
        self.structure_format_comboBox.setObjectName("structure_format_comboBox")
        self.structure_format_comboBox.addItem("")
        self.structure_format_comboBox.addItem("")
        self.horizontalLayout_25.addWidget(self.structure_format_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem29)
        self.generate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.generate_pushButton.setFont(font)
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.horizontalLayout_15.addWidget(self.generate_pushButton)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_29.addLayout(self.verticalLayout_2)
        self.line_8.raise_()
        self.nanogen_tabWidget.raise_()
        self.line_3.raise_()
        NanoGen.setCentralWidget(self.centralwidget)
        self.nanogen_statusBar = QtWidgets.QStatusBar(NanoGen)
        self.nanogen_statusBar.setObjectName("nanogen_statusBar")
        NanoGen.setStatusBar(self.nanogen_statusBar)

        self.retranslateUi(NanoGen)
        self.nanogen_tabWidget.setCurrentIndex(0)
        self.element1_comboBox.setCurrentIndex(3)
        self.element2_comboBox.setCurrentIndex(3)
        self.structure_format_comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(NanoGen)

    def retranslateUi(self, NanoGen):
        _translate = QtCore.QCoreApplication.translate
        NanoGen.setWindowTitle(_translate("NanoGen", "NanoGen"))
        self.label_7.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">n = </p></body></html>"))
        self.label_14.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">m = </p></body></html>"))
        self.label_4.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>"))
        self.label_13.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.swnt_Lz_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.swnt_fix_Lz_checkBox.setText(_translate("NanoGen", "Fix Lz"))
        self.swnt_bundle_generator_checkBox.setText(_translate("NanoGen", "Bundle Generator"))
        self.label.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_2.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.label_3.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>"))
        self.label_12.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.swnt_generator_tab), _translate("NanoGen", "SWNTs"))
        self.label_19.setText(_translate("NanoGen", "Generate from..."))
        self.mwnt_Ch_list_radioButton.setText(_translate("NanoGen", "(n, m) List"))
        __sortingEnabled = self.mwnt_Ch_listWidget.isSortingEnabled()
        self.mwnt_Ch_listWidget.setSortingEnabled(False)
        item = self.mwnt_Ch_listWidget.item(0)
        item.setText(_translate("NanoGen", "(5, 5)"))
        item = self.mwnt_Ch_listWidget.item(1)
        item.setText(_translate("NanoGen", "(10,10)"))
        item = self.mwnt_Ch_listWidget.item(2)
        item.setText(_translate("NanoGen", "(20, 20)"))
        self.mwnt_Ch_listWidget.setSortingEnabled(__sortingEnabled)
        self.mwnt_wall_parameters_radioButton.setText(_translate("NanoGen", "Wall Parameters"))
        self.label_24.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">N</span><span style=\" vertical-align:sub;\">walls </span>= </p></body></html>"))
        self.label_25.setText(_translate("NanoGen", "<html><head/><body><p>Wall <span style=\" font-style:italic;\">d</span><span style=\" vertical-align:sub;\">t,min </span>= </p></body></html>"))
        self.min_wall_diameter_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.label_23.setText(_translate("NanoGen", "<html><head/><body><p>Wall <span style=\" font-style:italic;\">d</span><span style=\" vertical-align:sub;\">t,max </span>= </p></body></html>"))
        self.max_wall_diameter_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.label_26.setText(_translate("NanoGen", "<html><head/><body><p>Wall <span style=\" font-family:\'Open Sans,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:14px; color:#333333; background-color:#f9f9f9;\">Δ</span><span style=\" font-style:italic;\">d</span><span style=\" vertical-align:sub;\">t,min </span>= </p></body></html>"))
        self.wall_spacing_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.label_5.setText(_translate("NanoGen", "Chiralities"))
        self.random_wall_chiralities_radioButton.setText(_translate("NanoGen", "Random"))
        self.armchair_wall_chiralities_radioButton.setText(_translate("NanoGen", "Armchair"))
        self.zigzag_wall_chiralities_radioButton.setText(_translate("NanoGen", "Zigzag"))
        self.achiral_wall_chiralities_radioButton.setText(_translate("NanoGen", "Achiral"))
        self.chiral_wall_chiralities_radioButton.setText(_translate("NanoGen", "Chiral"))
        self.label_20.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.mwnt_Lz_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.mwnt_bundle_generator_checkBox.setText(_translate("NanoGen", "Bundle Generator"))
        self.label_8.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_16.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.label_21.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>"))
        self.label_22.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.mwnt_generator_tab), _translate("NanoGen", "MWNTs"))
        self.label_33.setText(_translate("NanoGen", "Generate from..."))
        self.achiral_edge_lengths_radioButton.setText(_translate("NanoGen", "Achiral Edge Lengths"))
        self.label_9.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">armchair</span> =</p></body></html>"))
        self.armchair_edge_length_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.label_10.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">zigzag</span> =</p></body></html>"))
        self.zigzag_edge_length_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.unrolled_swnt_chirality_radioButton.setText(_translate("NanoGen", "(n, m) Chiral Indices"))
        self.label_27.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">n = </p></body></html>"))
        self.label_28.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">m = </p></body></html>"))
        self.label_31.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_32.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.unrolled_swnt_Lx_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.label_29.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>"))
        self.label_30.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.unrolled_swnt_Lz_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.label_11.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">layers</span> =</p></body></html>"))
        self.label_6.setText(_translate("NanoGen", "<html><head/><body><p>Stacking Order</p></body></html>"))
        self.AA_stacking_radioButton.setText(_translate("NanoGen", "AA"))
        self.AB_stacking_radioButton.setText(_translate("NanoGen", "AB"))
        self.label_15.setText(_translate("NanoGen", "<html><head/><body><p>deg/layer =</p></body></html>"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.graphene_generator_tab), _translate("NanoGen", "Graphene"))
        self.label_34.setText(_translate("NanoGen", "Select Fullerene from list..."))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.fullerene_generator_tab), _translate("NanoGen", "Fullerenes"))
        self.label_17.setText(_translate("NanoGen", "Element 1:"))
        self.element1_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.element1_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.element1_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.element1_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.element1_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.label_18.setText(_translate("NanoGen", "Element 2:"))
        self.element2_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.element2_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.element2_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.element2_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.element2_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.elements_bond_label.setText(_translate("NanoGen", "<html><head/><body><p>C-C bond =</p></body></html>"))
        self.bond_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.save_as_pushButton.setText(_translate("NanoGen", "Save As..."))
        self.structure_format_comboBox.setItemText(0, _translate("NanoGen", "data"))
        self.structure_format_comboBox.setItemText(1, _translate("NanoGen", "xyz"))
        self.generate_pushButton.setText(_translate("NanoGen", "Generate"))

