# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nanogen.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NanoGen(object):
    def setupUi(self, NanoGen):
        NanoGen.setObjectName("NanoGen")
        NanoGen.resize(500, 700)
        NanoGen.setMinimumSize(QtCore.QSize(500, 700))
        NanoGen.setMaximumSize(QtCore.QSize(500, 700))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        NanoGen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(NanoGen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.nanogen_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.nanogen_tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.nanogen_tabWidget.setFont(font)
        self.nanogen_tabWidget.setObjectName("nanogen_tabWidget")
        self.nanotube_generator_tabWidget = QtWidgets.QWidget()
        self.nanotube_generator_tabWidget.setObjectName("nanotube_generator_tabWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.nanotube_generator_tabWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nanotube_generator_radioButton = QtWidgets.QRadioButton(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nanotube_generator_radioButton.setFont(font)
        self.nanotube_generator_radioButton.setChecked(True)
        self.nanotube_generator_radioButton.setObjectName("nanotube_generator_radioButton")
        self.nanotube_generator_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.nanotube_generator_buttonGroup.setObjectName("nanotube_generator_buttonGroup")
        self.nanotube_generator_buttonGroup.addButton(self.nanotube_generator_radioButton)
        self.verticalLayout.addWidget(self.nanotube_generator_radioButton)
        self.capped_nanotube_generator_radioButton = QtWidgets.QRadioButton(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.capped_nanotube_generator_radioButton.setFont(font)
        self.capped_nanotube_generator_radioButton.setCheckable(False)
        self.capped_nanotube_generator_radioButton.setObjectName("capped_nanotube_generator_radioButton")
        self.nanotube_generator_buttonGroup.addButton(self.capped_nanotube_generator_radioButton)
        self.verticalLayout.addWidget(self.capped_nanotube_generator_radioButton)
        self.mwnt_generator_radioButton = QtWidgets.QRadioButton(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mwnt_generator_radioButton.setFont(font)
        self.mwnt_generator_radioButton.setObjectName("mwnt_generator_radioButton")
        self.nanotube_generator_buttonGroup.addButton(self.mwnt_generator_radioButton)
        self.verticalLayout.addWidget(self.mwnt_generator_radioButton)
        self.unrolled_nanotube_generator_radioButton = QtWidgets.QRadioButton(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.unrolled_nanotube_generator_radioButton.setFont(font)
        self.unrolled_nanotube_generator_radioButton.setObjectName("unrolled_nanotube_generator_radioButton")
        self.nanotube_generator_buttonGroup.addButton(self.unrolled_nanotube_generator_radioButton)
        self.verticalLayout.addWidget(self.unrolled_nanotube_generator_radioButton)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bundle_generator_checkBox = QtWidgets.QCheckBox(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bundle_generator_checkBox.setFont(font)
        self.bundle_generator_checkBox.setCheckable(True)
        self.bundle_generator_checkBox.setObjectName("bundle_generator_checkBox")
        self.horizontalLayout_23.addWidget(self.bundle_generator_checkBox)
        self.fix_Lz_checkBox = QtWidgets.QCheckBox(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fix_Lz_checkBox.setFont(font)
        self.fix_Lz_checkBox.setCheckable(True)
        self.fix_Lz_checkBox.setObjectName("fix_Lz_checkBox")
        self.horizontalLayout_23.addWidget(self.fix_Lz_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.line = QtWidgets.QFrame(self.nanotube_generator_tabWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.n_spinBox = QtWidgets.QSpinBox(self.nanotube_generator_tabWidget)
        self.n_spinBox.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.n_spinBox.setFont(font)
        self.n_spinBox.setMaximum(100)
        self.n_spinBox.setProperty("value", 10)
        self.n_spinBox.setObjectName("n_spinBox")
        self.horizontalLayout_2.addWidget(self.n_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.m_spinBox = QtWidgets.QSpinBox(self.nanotube_generator_tabWidget)
        self.m_spinBox.setMinimumSize(QtCore.QSize(90, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.m_spinBox.setFont(font)
        self.m_spinBox.setMaximum(100)
        self.m_spinBox.setProperty("value", 10)
        self.m_spinBox.setObjectName("m_spinBox")
        self.horizontalLayout.addWidget(self.m_spinBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.line_2 = QtWidgets.QFrame(self.nanotube_generator_tabWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.nanotube_element1_comboBox = QtWidgets.QComboBox(self.nanotube_generator_tabWidget)
        self.nanotube_element1_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.nanotube_element1_comboBox.setObjectName("nanotube_element1_comboBox")
        self.nanotube_element1_comboBox.addItem("")
        self.nanotube_element1_comboBox.addItem("")
        self.nanotube_element1_comboBox.addItem("")
        self.nanotube_element1_comboBox.addItem("")
        self.nanotube_element1_comboBox.addItem("")
        self.horizontalLayout_29.addWidget(self.nanotube_element1_comboBox)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_18 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_28.addWidget(self.label_18)
        self.nanotube_element2_comboBox = QtWidgets.QComboBox(self.nanotube_generator_tabWidget)
        self.nanotube_element2_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.nanotube_element2_comboBox.setObjectName("nanotube_element2_comboBox")
        self.nanotube_element2_comboBox.addItem("")
        self.nanotube_element2_comboBox.addItem("")
        self.nanotube_element2_comboBox.addItem("")
        self.nanotube_element2_comboBox.addItem("")
        self.nanotube_element2_comboBox.addItem("")
        self.horizontalLayout_28.addWidget(self.nanotube_element2_comboBox)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_30)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.nanotube_e1e2_bond_label = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nanotube_e1e2_bond_label.setFont(font)
        self.nanotube_e1e2_bond_label.setObjectName("nanotube_e1e2_bond_label")
        self.horizontalLayout_14.addWidget(self.nanotube_e1e2_bond_label)
        self.nanotube_bond_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanotube_bond_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.nanotube_bond_doubleSpinBox.setSizePolicy(sizePolicy)
        self.nanotube_bond_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nanotube_bond_doubleSpinBox.setFont(font)
        self.nanotube_bond_doubleSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.nanotube_bond_doubleSpinBox.setReadOnly(False)
        self.nanotube_bond_doubleSpinBox.setDecimals(3)
        self.nanotube_bond_doubleSpinBox.setMinimum(0.5)
        self.nanotube_bond_doubleSpinBox.setMaximum(10.0)
        self.nanotube_bond_doubleSpinBox.setSingleStep(0.01)
        self.nanotube_bond_doubleSpinBox.setProperty("value", 1.42)
        self.nanotube_bond_doubleSpinBox.setObjectName("nanotube_bond_doubleSpinBox")
        self.horizontalLayout_14.addWidget(self.nanotube_bond_doubleSpinBox)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.line_8 = QtWidgets.QFrame(self.nanotube_generator_tabWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.nx_spinBox = QtWidgets.QSpinBox(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nx_spinBox.sizePolicy().hasHeightForWidth())
        self.nx_spinBox.setSizePolicy(sizePolicy)
        self.nx_spinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nx_spinBox.setFont(font)
        self.nx_spinBox.setMinimum(1)
        self.nx_spinBox.setObjectName("nx_spinBox")
        self.horizontalLayout_4.addWidget(self.nx_spinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.Lx_lineEdit = QtWidgets.QLineEdit(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lx_lineEdit.sizePolicy().hasHeightForWidth())
        self.Lx_lineEdit.setSizePolicy(sizePolicy)
        self.Lx_lineEdit.setMinimumSize(QtCore.QSize(175, 36))
        self.Lx_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Lx_lineEdit.setReadOnly(True)
        self.Lx_lineEdit.setObjectName("Lx_lineEdit")
        self.horizontalLayout_7.addWidget(self.Lx_lineEdit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.ny_spinBox = QtWidgets.QSpinBox(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ny_spinBox.sizePolicy().hasHeightForWidth())
        self.ny_spinBox.setSizePolicy(sizePolicy)
        self.ny_spinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ny_spinBox.setFont(font)
        self.ny_spinBox.setMinimum(1)
        self.ny_spinBox.setObjectName("ny_spinBox")
        self.horizontalLayout_5.addWidget(self.ny_spinBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.Ly_lineEdit = QtWidgets.QLineEdit(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ly_lineEdit.sizePolicy().hasHeightForWidth())
        self.Ly_lineEdit.setSizePolicy(sizePolicy)
        self.Ly_lineEdit.setMinimumSize(QtCore.QSize(175, 36))
        self.Ly_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Ly_lineEdit.setReadOnly(True)
        self.Ly_lineEdit.setObjectName("Ly_lineEdit")
        self.horizontalLayout_8.addWidget(self.Ly_lineEdit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.nz_spinBox = QtWidgets.QSpinBox(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nz_spinBox.sizePolicy().hasHeightForWidth())
        self.nz_spinBox.setSizePolicy(sizePolicy)
        self.nz_spinBox.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nz_spinBox.setFont(font)
        self.nz_spinBox.setMinimum(1)
        self.nz_spinBox.setMaximum(1000)
        self.nz_spinBox.setProperty("value", 1000)
        self.nz_spinBox.setObjectName("nz_spinBox")
        self.horizontalLayout_6.addWidget(self.nz_spinBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.nanotube_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.Lz_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.nanotube_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lz_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.Lz_doubleSpinBox.setSizePolicy(sizePolicy)
        self.Lz_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Lz_doubleSpinBox.setFont(font)
        self.Lz_doubleSpinBox.setDecimals(4)
        self.Lz_doubleSpinBox.setMaximum(1000.0)
        self.Lz_doubleSpinBox.setObjectName("Lz_doubleSpinBox")
        self.horizontalLayout_9.addWidget(self.Lz_doubleSpinBox)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.nanogen_tabWidget.addTab(self.nanotube_generator_tabWidget, "")
        self.graphene_generator_tabWidget = QtWidgets.QWidget()
        self.graphene_generator_tabWidget.setObjectName("graphene_generator_tabWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.graphene_generator_tabWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_10 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.armchair_edge_length_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tabWidget)
        self.armchair_edge_length_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.armchair_edge_length_doubleSpinBox.setFont(font)
        self.armchair_edge_length_doubleSpinBox.setDecimals(4)
        self.armchair_edge_length_doubleSpinBox.setMaximum(1000.0)
        self.armchair_edge_length_doubleSpinBox.setProperty("value", 10.0)
        self.armchair_edge_length_doubleSpinBox.setObjectName("armchair_edge_length_doubleSpinBox")
        self.horizontalLayout_16.addWidget(self.armchair_edge_length_doubleSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.zigzag_edge_length_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tabWidget)
        self.zigzag_edge_length_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zigzag_edge_length_doubleSpinBox.setFont(font)
        self.zigzag_edge_length_doubleSpinBox.setDecimals(4)
        self.zigzag_edge_length_doubleSpinBox.setMaximum(1000.0)
        self.zigzag_edge_length_doubleSpinBox.setProperty("value", 1.0)
        self.zigzag_edge_length_doubleSpinBox.setObjectName("zigzag_edge_length_doubleSpinBox")
        self.horizontalLayout_17.addWidget(self.zigzag_edge_length_doubleSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addLayout(self.verticalLayout_9)
        self.line_5 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_19.addWidget(self.line_5)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.AC_edge_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tabWidget)
        self.AC_edge_radioButton.setChecked(True)
        self.AC_edge_radioButton.setObjectName("AC_edge_radioButton")
        self.Lx_edge_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.Lx_edge_buttonGroup.setObjectName("Lx_edge_buttonGroup")
        self.Lx_edge_buttonGroup.addButton(self.AC_edge_radioButton)
        self.verticalLayout_3.addWidget(self.AC_edge_radioButton)
        self.ZZ_edge_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tabWidget)
        self.ZZ_edge_radioButton.setObjectName("ZZ_edge_radioButton")
        self.Lx_edge_buttonGroup.addButton(self.ZZ_edge_radioButton)
        self.verticalLayout_3.addWidget(self.ZZ_edge_radioButton)
        self.horizontalLayout_20.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.line_4 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_19 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_34.addWidget(self.label_19)
        self.graphene_element1_comboBox = QtWidgets.QComboBox(self.graphene_generator_tabWidget)
        self.graphene_element1_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.graphene_element1_comboBox.setObjectName("graphene_element1_comboBox")
        self.graphene_element1_comboBox.addItem("")
        self.graphene_element1_comboBox.addItem("")
        self.graphene_element1_comboBox.addItem("")
        self.graphene_element1_comboBox.addItem("")
        self.graphene_element1_comboBox.addItem("")
        self.horizontalLayout_34.addWidget(self.graphene_element1_comboBox)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_20 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_35.addWidget(self.label_20)
        self.graphene_element2_comboBox = QtWidgets.QComboBox(self.graphene_generator_tabWidget)
        self.graphene_element2_comboBox.setMinimumSize(QtCore.QSize(0, 36))
        self.graphene_element2_comboBox.setObjectName("graphene_element2_comboBox")
        self.graphene_element2_comboBox.addItem("")
        self.graphene_element2_comboBox.addItem("")
        self.graphene_element2_comboBox.addItem("")
        self.graphene_element2_comboBox.addItem("")
        self.graphene_element2_comboBox.addItem("")
        self.horizontalLayout_35.addWidget(self.graphene_element2_comboBox)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_33)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.graphene_e1e2_bond_label = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.graphene_e1e2_bond_label.setFont(font)
        self.graphene_e1e2_bond_label.setObjectName("graphene_e1e2_bond_label")
        self.horizontalLayout_36.addWidget(self.graphene_e1e2_bond_label)
        self.graphene_bond_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tabWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphene_bond_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.graphene_bond_doubleSpinBox.setSizePolicy(sizePolicy)
        self.graphene_bond_doubleSpinBox.setMinimumSize(QtCore.QSize(150, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.graphene_bond_doubleSpinBox.setFont(font)
        self.graphene_bond_doubleSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.graphene_bond_doubleSpinBox.setReadOnly(False)
        self.graphene_bond_doubleSpinBox.setDecimals(3)
        self.graphene_bond_doubleSpinBox.setMinimum(0.5)
        self.graphene_bond_doubleSpinBox.setMaximum(10.0)
        self.graphene_bond_doubleSpinBox.setSingleStep(0.01)
        self.graphene_bond_doubleSpinBox.setProperty("value", 1.42)
        self.graphene_bond_doubleSpinBox.setObjectName("graphene_bond_doubleSpinBox")
        self.horizontalLayout_36.addWidget(self.graphene_bond_doubleSpinBox)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_36)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.line_7 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.nlayers_spinBox = QtWidgets.QSpinBox(self.graphene_generator_tabWidget)
        self.nlayers_spinBox.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nlayers_spinBox.setFont(font)
        self.nlayers_spinBox.setMinimum(1)
        self.nlayers_spinBox.setMaximum(50)
        self.nlayers_spinBox.setObjectName("nlayers_spinBox")
        self.horizontalLayout_18.addWidget(self.nlayers_spinBox)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_18)
        self.line_6 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_21.addWidget(self.line_6)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.AA_stacking_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AA_stacking_radioButton.setFont(font)
        self.AA_stacking_radioButton.setCheckable(True)
        self.AA_stacking_radioButton.setChecked(True)
        self.AA_stacking_radioButton.setObjectName("AA_stacking_radioButton")
        self.stacking_order_buttonGroup = QtWidgets.QButtonGroup(NanoGen)
        self.stacking_order_buttonGroup.setObjectName("stacking_order_buttonGroup")
        self.stacking_order_buttonGroup.addButton(self.AA_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AA_stacking_radioButton)
        self.AB_stacking_radioButton = QtWidgets.QRadioButton(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AB_stacking_radioButton.setFont(font)
        self.AB_stacking_radioButton.setCheckable(True)
        self.AB_stacking_radioButton.setObjectName("AB_stacking_radioButton")
        self.stacking_order_buttonGroup.addButton(self.AB_stacking_radioButton)
        self.verticalLayout_4.addWidget(self.AB_stacking_radioButton)
        self.horizontalLayout_22.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_15 = QtWidgets.QLabel(self.graphene_generator_tabWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_26.addWidget(self.label_15)
        self.layer_rotation_increment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphene_generator_tabWidget)
        self.layer_rotation_increment_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 36))
        self.layer_rotation_increment_doubleSpinBox.setObjectName("layer_rotation_increment_doubleSpinBox")
        self.horizontalLayout_26.addWidget(self.layer_rotation_increment_doubleSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_37.addLayout(self.verticalLayout_8)
        spacerItem9 = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_37)
        self.line_9 = QtWidgets.QFrame(self.graphene_generator_tabWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem10)
        self.nanogen_tabWidget.addTab(self.graphene_generator_tabWidget, "")
        self.fullerene_generators = QtWidgets.QWidget()
        self.fullerene_generators.setObjectName("fullerene_generators")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.fullerene_generators)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.listWidget = QtWidgets.QListWidget(self.fullerene_generators)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_11.addWidget(self.listWidget)
        self.nanogen_tabWidget.addTab(self.fullerene_generators, "")
        self.horizontalLayout_38.addWidget(self.nanogen_tabWidget)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_38)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.save_as_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_as_pushButton.setObjectName("save_as_pushButton")
        self.horizontalLayout_25.addWidget(self.save_as_pushButton)
        self.fpath_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fpath_lineEdit.setFont(font)
        self.fpath_lineEdit.setObjectName("fpath_lineEdit")
        self.horizontalLayout_25.addWidget(self.fpath_lineEdit)
        self.structure_format_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.structure_format_comboBox.setMinimumSize(QtCore.QSize(80, 36))
        self.structure_format_comboBox.setMaximumSize(QtCore.QSize(120, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.structure_format_comboBox.setFont(font)
        self.structure_format_comboBox.setModelColumn(0)
        self.structure_format_comboBox.setObjectName("structure_format_comboBox")
        self.structure_format_comboBox.addItem("")
        self.structure_format_comboBox.addItem("")
        self.horizontalLayout_25.addWidget(self.structure_format_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.generate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.generate_pushButton.setFont(font)
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.horizontalLayout_15.addWidget(self.generate_pushButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        NanoGen.setCentralWidget(self.centralwidget)
        self.nanogen_statusBar = QtWidgets.QStatusBar(NanoGen)
        self.nanogen_statusBar.setObjectName("nanogen_statusBar")
        NanoGen.setStatusBar(self.nanogen_statusBar)

        self.retranslateUi(NanoGen)
        self.nanogen_tabWidget.setCurrentIndex(0)
        self.nanotube_element1_comboBox.setCurrentIndex(3)
        self.nanotube_element2_comboBox.setCurrentIndex(3)
        self.graphene_element1_comboBox.setCurrentIndex(3)
        self.graphene_element2_comboBox.setCurrentIndex(3)
        self.structure_format_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NanoGen)

    def retranslateUi(self, NanoGen):
        _translate = QtCore.QCoreApplication.translate
        NanoGen.setWindowTitle(_translate("NanoGen", "NanoGen"))
        self.nanotube_generator_radioButton.setText(_translate("NanoGen", "Nanotube Generator"))
        self.capped_nanotube_generator_radioButton.setText(_translate("NanoGen", "Capped Nanotube Generator"))
        self.mwnt_generator_radioButton.setText(_translate("NanoGen", "Multi-walled Nanotube Generator"))
        self.unrolled_nanotube_generator_radioButton.setText(_translate("NanoGen", "Unrolled Nanotube Generator"))
        self.bundle_generator_checkBox.setText(_translate("NanoGen", "Bundle Generator"))
        self.fix_Lz_checkBox.setText(_translate("NanoGen", "Fix Lz"))
        self.label_7.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">n = </p></body></html>"))
        self.label_14.setText(_translate("NanoGen", "<html><head/><body><p align=\"right\">m = </p></body></html>"))
        self.label_17.setText(_translate("NanoGen", "Element 1:"))
        self.nanotube_element1_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.nanotube_element1_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.nanotube_element1_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.nanotube_element1_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.nanotube_element1_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.label_18.setText(_translate("NanoGen", "Element 2:"))
        self.nanotube_element2_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.nanotube_element2_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.nanotube_element2_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.nanotube_element2_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.nanotube_element2_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.nanotube_e1e2_bond_label.setText(_translate("NanoGen", "<html><head/><body><p>C-C bond =</p></body></html>"))
        self.nanotube_bond_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.label.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">x </span>=</p></body></html>"))
        self.label_2.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x </span>= </p></body></html>"))
        self.label_3.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">y </span>=</p></body></html>"))
        self.label_12.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y </span>= </p></body></html>"))
        self.label_4.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">z </span>=</p></body></html>"))
        self.label_13.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">z </span>= </p></body></html>"))
        self.Lz_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.nanotube_generator_tabWidget), _translate("NanoGen", "Nanotubes"))
        self.label_9.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x</span> =</p></body></html>"))
        self.armchair_edge_length_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.label_10.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">y</span> =</p></body></html>"))
        self.zigzag_edge_length_doubleSpinBox.setSuffix(_translate("NanoGen", " nm"))
        self.label_5.setText(_translate("NanoGen", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">L</span><span style=\" vertical-align:sub;\">x</span> edge</p></body></html>"))
        self.AC_edge_radioButton.setText(_translate("NanoGen", "armchair"))
        self.ZZ_edge_radioButton.setText(_translate("NanoGen", "zigzag"))
        self.label_19.setText(_translate("NanoGen", "Element 1:"))
        self.graphene_element1_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.graphene_element1_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.graphene_element1_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.graphene_element1_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.graphene_element1_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.label_20.setText(_translate("NanoGen", "Element 2:"))
        self.graphene_element2_comboBox.setItemText(0, _translate("NanoGen", "H"))
        self.graphene_element2_comboBox.setItemText(1, _translate("NanoGen", "He"))
        self.graphene_element2_comboBox.setItemText(2, _translate("NanoGen", "B"))
        self.graphene_element2_comboBox.setItemText(3, _translate("NanoGen", "C"))
        self.graphene_element2_comboBox.setItemText(4, _translate("NanoGen", "N"))
        self.graphene_e1e2_bond_label.setText(_translate("NanoGen", "<html><head/><body><p>C-C bond =</p></body></html>"))
        self.graphene_bond_doubleSpinBox.setSuffix(_translate("NanoGen", " Å"))
        self.label_11.setText(_translate("NanoGen", "<html><head/><body><p><span style=\" font-style:italic;\">n</span><span style=\" vertical-align:sub;\">layers</span> =</p></body></html>"))
        self.label_6.setText(_translate("NanoGen", "<html><head/><body><p>Stacking Order</p></body></html>"))
        self.AA_stacking_radioButton.setText(_translate("NanoGen", "AA"))
        self.AB_stacking_radioButton.setText(_translate("NanoGen", "AB"))
        self.label_15.setText(_translate("NanoGen", "<html><head/><body><p>deg/layer =</p></body></html>"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.graphene_generator_tabWidget), _translate("NanoGen", "Graphene"))
        self.nanogen_tabWidget.setTabText(self.nanogen_tabWidget.indexOf(self.fullerene_generators), _translate("NanoGen", "Fullerenes"))
        self.save_as_pushButton.setText(_translate("NanoGen", "Save As..."))
        self.structure_format_comboBox.setItemText(0, _translate("NanoGen", "data"))
        self.structure_format_comboBox.setItemText(1, _translate("NanoGen", "xyz"))
        self.generate_pushButton.setText(_translate("NanoGen", "Generate"))

